# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Views\layout_newOrder.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1344, 867)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(110, 70, 1023, 721))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.ui_layout_newOrder = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.ui_layout_newOrder.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.ui_layout_newOrder.setContentsMargins(0, 0, 0, 0)
        self.ui_layout_newOrder.setSpacing(6)
        self.ui_layout_newOrder.setObjectName("ui_layout_newOrder")
        self.ux_label_selectProd = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_label_selectProd.sizePolicy().hasHeightForWidth())
        self.ux_label_selectProd.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ux_label_selectProd.setFont(font)
        self.ux_label_selectProd.setAlignment(QtCore.Qt.AlignCenter)
        self.ux_label_selectProd.setObjectName("ux_label_selectProd")
        self.ui_layout_newOrder.addWidget(self.ux_label_selectProd, 11, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.ui_layout_newOrder.addItem(spacerItem, 14, 4, 1, 1)
        self.ux_pButton_addProdToOrd = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_pButton_addProdToOrd.sizePolicy().hasHeightForWidth())
        self.ux_pButton_addProdToOrd.setSizePolicy(sizePolicy)
        self.ux_pButton_addProdToOrd.setMinimumSize(QtCore.QSize(280, 0))
        self.ux_pButton_addProdToOrd.setObjectName("ux_pButton_addProdToOrd")
        self.ui_layout_newOrder.addWidget(self.ux_pButton_addProdToOrd, 14, 0, 1, 1)
        self.ux_label_prodInCurOrder = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ux_label_prodInCurOrder.setFont(font)
        self.ux_label_prodInCurOrder.setAlignment(QtCore.Qt.AlignCenter)
        self.ux_label_prodInCurOrder.setObjectName("ux_label_prodInCurOrder")
        self.ui_layout_newOrder.addWidget(self.ux_label_prodInCurOrder, 11, 3, 1, 2)
        self.ux_comboBox_clientName = QtWidgets.QComboBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_comboBox_clientName.sizePolicy().hasHeightForWidth())
        self.ux_comboBox_clientName.setSizePolicy(sizePolicy)
        self.ux_comboBox_clientName.setMinimumSize(QtCore.QSize(200, 0))
        self.ux_comboBox_clientName.setObjectName("ux_comboBox_clientName")
        self.ui_layout_newOrder.addWidget(self.ux_comboBox_clientName, 1, 2, 1, 1)
        self.ux_label_orderNumber = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_label_orderNumber.sizePolicy().hasHeightForWidth())
        self.ux_label_orderNumber.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ux_label_orderNumber.setFont(font)
        self.ux_label_orderNumber.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ux_label_orderNumber.setObjectName("ux_label_orderNumber")
        self.ui_layout_newOrder.addWidget(self.ux_label_orderNumber, 0, 0, 1, 1)
        self.ux_tableWidget_curProducts = QtWidgets.QTableWidget(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_tableWidget_curProducts.sizePolicy().hasHeightForWidth())
        self.ux_tableWidget_curProducts.setSizePolicy(sizePolicy)
        self.ux_tableWidget_curProducts.setMinimumSize(QtCore.QSize(290, 0))
        self.ux_tableWidget_curProducts.setShowGrid(True)
        self.ux_tableWidget_curProducts.setRowCount(0)
        self.ux_tableWidget_curProducts.setColumnCount(2)
        self.ux_tableWidget_curProducts.setObjectName("ux_tableWidget_curProducts")
        item = QtWidgets.QTableWidgetItem()
        self.ux_tableWidget_curProducts.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ux_tableWidget_curProducts.setHorizontalHeaderItem(1, item)
        self.ux_tableWidget_curProducts.horizontalHeader().setCascadingSectionResizes(False)
        self.ux_tableWidget_curProducts.horizontalHeader().setDefaultSectionSize(140)
        self.ux_tableWidget_curProducts.verticalHeader().setVisible(False)
        self.ui_layout_newOrder.addWidget(self.ux_tableWidget_curProducts, 12, 0, 1, 1)
        self.ux_pButton_revAndComp = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ux_pButton_revAndComp.setObjectName("ux_pButton_revAndComp")
        self.ui_layout_newOrder.addWidget(self.ux_pButton_revAndComp, 15, 3, 1, 2)
        self.ux_label_clientName = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_label_clientName.sizePolicy().hasHeightForWidth())
        self.ux_label_clientName.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ux_label_clientName.setFont(font)
        self.ux_label_clientName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ux_label_clientName.setObjectName("ux_label_clientName")
        self.ui_layout_newOrder.addWidget(self.ux_label_clientName, 1, 0, 1, 1)
        self.ux_label_deliveryDate = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_label_deliveryDate.sizePolicy().hasHeightForWidth())
        self.ux_label_deliveryDate.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ux_label_deliveryDate.setFont(font)
        self.ux_label_deliveryDate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ux_label_deliveryDate.setObjectName("ux_label_deliveryDate")
        self.ui_layout_newOrder.addWidget(self.ux_label_deliveryDate, 4, 0, 1, 1)
        self.ux_lineEdit_orderNumber = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_lineEdit_orderNumber.sizePolicy().hasHeightForWidth())
        self.ux_lineEdit_orderNumber.setSizePolicy(sizePolicy)
        self.ux_lineEdit_orderNumber.setMinimumSize(QtCore.QSize(200, 0))
        self.ux_lineEdit_orderNumber.setObjectName("ux_lineEdit_orderNumber")
        self.ui_layout_newOrder.addWidget(self.ux_lineEdit_orderNumber, 0, 2, 1, 1)
        self.ux_pButton_compOrder = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ux_pButton_compOrder.setObjectName("ux_pButton_compOrder")
        self.ui_layout_newOrder.addWidget(self.ux_pButton_compOrder, 13, 3, 1, 2)
        self.ux_tableWidget_orderProducts = QtWidgets.QTableWidget(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_tableWidget_orderProducts.sizePolicy().hasHeightForWidth())
        self.ux_tableWidget_orderProducts.setSizePolicy(sizePolicy)
        self.ux_tableWidget_orderProducts.setShowGrid(True)
        self.ux_tableWidget_orderProducts.setRowCount(0)
        self.ux_tableWidget_orderProducts.setColumnCount(4)
        self.ux_tableWidget_orderProducts.setObjectName("ux_tableWidget_orderProducts")
        item = QtWidgets.QTableWidgetItem()
        self.ux_tableWidget_orderProducts.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ux_tableWidget_orderProducts.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ux_tableWidget_orderProducts.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ux_tableWidget_orderProducts.setHorizontalHeaderItem(3, item)
        self.ux_tableWidget_orderProducts.horizontalHeader().setDefaultSectionSize(120)
        self.ui_layout_newOrder.addWidget(self.ux_tableWidget_orderProducts, 12, 3, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.ui_layout_newOrder.addItem(spacerItem1, 5, 2, 1, 1)
        self.ux_lineEdit_deliveryDate = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_lineEdit_deliveryDate.sizePolicy().hasHeightForWidth())
        self.ux_lineEdit_deliveryDate.setSizePolicy(sizePolicy)
        self.ux_lineEdit_deliveryDate.setMinimumSize(QtCore.QSize(200, 0))
        self.ux_lineEdit_deliveryDate.setObjectName("ux_lineEdit_deliveryDate")
        self.ui_layout_newOrder.addWidget(self.ux_lineEdit_deliveryDate, 4, 2, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.ux_label_selectProd.setText(_translate("Form", "Select Products for Current Order:"))
        self.ux_pButton_addProdToOrd.setText(_translate("Form", "Add Product To Order"))
        self.ux_label_prodInCurOrder.setText(_translate("Form", "Products in Current Order:"))
        self.ux_label_orderNumber.setText(_translate("Form", "Facture/Order #:"))
        item = self.ux_tableWidget_curProducts.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Product Name"))
        item = self.ux_tableWidget_curProducts.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Price-Per-Unit"))
        self.ux_pButton_revAndComp.setText(_translate("Form", "Review and Complete Order"))
        self.ux_label_clientName.setText(_translate("Form", "Client Name:"))
        self.ux_label_deliveryDate.setText(_translate("Form", "Delivery Date:"))
        self.ux_pButton_compOrder.setText(_translate("Form", "Remove Product From Order"))
        item = self.ux_tableWidget_orderProducts.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Product Name"))
        item = self.ux_tableWidget_orderProducts.horizontalHeaderItem(1)
        item.setText(_translate("Form", "New Column"))
        item = self.ux_tableWidget_orderProducts.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Unit Amount"))
        item = self.ux_tableWidget_orderProducts.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Total Cost"))
