# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Views\view_main_ui_v2base.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
#
#   core concept credit for dynamic pages using QStacked objects: nathancy @ https://stackoverflow.com/a/55911336
#
#
#######################################################################################################


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_mainView(object):
    def setupUi(self, main_view):

        # init main window
        main_view.setObjectName("main_view")
        main_view.resize(1200, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(main_view.sizePolicy().hasHeightForWidth())
        main_view.setSizePolicy(sizePolicy)
        main_view.setFixedSize(main_view.size())


        # init top-level QWidget in main window
        self.centralwidget = QtWidgets.QWidget(main_view)
        self.centralwidget.setObjectName("centralwidget")

        # init QWidget holding the left-most vertical layout
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, 0, 131, 721))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")

        # init left-most vertical layout (holds left buttons)
        self.ui_vLayout_viewMain = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.ui_vLayout_viewMain.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.ui_vLayout_viewMain.setContentsMargins(0, 0, 0, 0)
        self.ui_vLayout_viewMain.setSpacing(0)
        self.ui_vLayout_viewMain.setObjectName("ui_vLayout_viewMain")

        # init buttons within ui_vLayout_viewMain
        self.ux_pButton_orders = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_pButton_orders.sizePolicy().hasHeightForWidth())
        self.ux_pButton_orders.setSizePolicy(sizePolicy)
        self.ux_pButton_orders.setBaseSize(QtCore.QSize(0, 0))
        self.ux_pButton_orders.setObjectName("ux_pButton_orders")
        self.ui_vLayout_viewMain.addWidget(self.ux_pButton_orders)
        self.ux_pButton_clients = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_pButton_clients.sizePolicy().hasHeightForWidth())
        self.ux_pButton_clients.setSizePolicy(sizePolicy)
        self.ux_pButton_clients.setObjectName("ux_pButton_clients")
        self.ui_vLayout_viewMain.addWidget(self.ux_pButton_clients)
        self.ux_pButton_products = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_pButton_products.sizePolicy().hasHeightForWidth())
        self.ux_pButton_products.setSizePolicy(sizePolicy)
        self.ux_pButton_products.setObjectName("ux_pButton_products")
        self.ui_vLayout_viewMain.addWidget(self.ux_pButton_products)
        self.ux_pButton_invoicing = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_pButton_invoicing.sizePolicy().hasHeightForWidth())
        self.ux_pButton_invoicing.setSizePolicy(sizePolicy)
        self.ux_pButton_invoicing.setObjectName("ux_pButton_invoicing")
        self.ui_vLayout_viewMain.addWidget(self.ux_pButton_invoicing)
        self.ux_pButton_statistics = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_pButton_statistics.sizePolicy().hasHeightForWidth())
        self.ux_pButton_statistics.setSizePolicy(sizePolicy)
        self.ux_pButton_statistics.setObjectName("ux_pButton_statistics")
        self.ui_vLayout_viewMain.addWidget(self.ux_pButton_statistics)
        self.ux_pButton_settings = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_pButton_settings.sizePolicy().hasHeightForWidth())
        self.ux_pButton_settings.setSizePolicy(sizePolicy)
        self.ux_pButton_settings.setObjectName("ux_pButton_settings")
        self.ui_vLayout_viewMain.addWidget(self.ux_pButton_settings)

        # init 2nd level buttons (e.g. New Orders)
        self.ux_pButton_searchEditOrders = QtWidgets.QPushButton(self.centralwidget)
        self.ux_pButton_searchEditOrders.setGeometry(QtCore.QRect(130, 60, 161, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_pButton_searchEditOrders.sizePolicy().hasHeightForWidth())
        self.ux_pButton_searchEditOrders.setSizePolicy(sizePolicy)
        self.ux_pButton_searchEditOrders.setObjectName("ux_pButton_searchEditOrders")
        self.ux_pButton_newOrder = QtWidgets.QPushButton(self.centralwidget)
        self.ux_pButton_newOrder.setGeometry(QtCore.QRect(130, 0, 161, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_pButton_newOrder.sizePolicy().hasHeightForWidth())
        self.ux_pButton_newOrder.setSizePolicy(sizePolicy)
        self.ux_pButton_newOrder.setObjectName("ux_pButton_newOrder")


        # init stacked layout widget; this is the top-level widget that holds the various
        #                               pages that change with button clicks
        self.stackedLayoutWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedLayoutWidget.setGeometry(QtCore.QRect(310, 20, 871, 681))
        self.stackedLayoutWidget.setObjectName("stackedLayoutWidget")

        # init all layout widgets to be displayed in the stackedLayoutWidget box
        self.ui_welcome(self.stackedLayoutWidget)
        self.ui_newOrder(self.stackedLayoutWidget)

        # set first shown widget (welcome)
        self.stackedLayoutWidget.setCurrentWidget(self.widget_welcomeLayout)

        main_view.setCentralWidget(self.centralwidget)

        self.retranslateUi(main_view)
        QtCore.QMetaObject.connectSlotsByName(main_view)

    def retranslateUi(self, MainWindow_mainView):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_mainView.setWindowTitle(_translate("main_view", "MainWindow"))
        self.ux_pButton_orders.setText(_translate("main_view", "Orders"))
        self.ux_pButton_clients.setText(_translate("main_view", "Clients"))
        self.ux_pButton_products.setText(_translate("main_view", "Products"))
        self.ux_pButton_invoicing.setText(_translate("main_view", "Invoicing"))
        self.ux_pButton_statistics.setText(_translate("main_view", "Statistics"))
        self.ux_pButton_settings.setText(_translate("main_view", "Settings"))
        self.ux_pButton_searchEditOrders.setText(_translate("main_view", "Search/Edit Orders"))
        self.ux_pButton_newOrder.setText(_translate("main_view", "New Order"))
        self.ux_label_welcome.setText(_translate("main_view", "Welcome!"))
        self.ux_label_clientName.setText(_translate("main_view", "Client Name:"))
        self.ux_label_deliveryDate.setText(_translate("main_view", "Delivery Date:"))
        self.ux_label_orderNumber.setText(_translate("main_view", "Facture/Order #:"))
        self.ux_label_prodInCurOrder.setText(_translate("main_view", "Products in Current Order:"))
        item = self.ux_tableWidget_curProducts.horizontalHeaderItem(0)
        item.setText(_translate("main_view", "Product Name"))
        item = self.ux_tableWidget_curProducts.horizontalHeaderItem(1)
        item.setText(_translate("main_view", "Price-Per-Unit"))
        item = self.ux_tableWidget_orderProducts.horizontalHeaderItem(0)
        item.setText(_translate("main_view", "Product Name"))
        item = self.ux_tableWidget_orderProducts.horizontalHeaderItem(1)
        item.setText(_translate("main_view", "New Column"))
        item = self.ux_tableWidget_orderProducts.horizontalHeaderItem(2)
        item.setText(_translate("main_view", "Unit Amount"))
        item = self.ux_tableWidget_orderProducts.horizontalHeaderItem(3)
        item.setText(_translate("main_view", "Total Cost"))
        self.ux_pButton_compOrder.setText(_translate("main_view", "Remove Product From Order"))
        self.ux_pButton_revAndComp.setText(_translate("main_view", "Review and Complete Order"))
        self.ux_pButton_addProdToOrd.setText(_translate("main_view", "Add Product To Order"))
        self.ux_label_selectProd.setText(_translate("main_view", "Select Products for Current Order:"))

    # init welcome window widget
    def ui_welcome(self, stackedLayoutWidget):
        # init welcome window widget; widget that represents the welcome window (first window)
        self.widget_welcomeLayout = QtWidgets.QWidget(self.stackedLayoutWidget)
        self.widget_welcomeLayout.setGeometry(QtCore.QRect(290, 0, 911, 721))
        self.widget_welcomeLayout.setObjectName("welcomeLayoutWidget")

        # init layout for welcome window
        self.ui_layout_welcomePage = QtWidgets.QGridLayout(self.widget_welcomeLayout)
        self.ui_layout_welcomePage.setGeometry(QtCore.QRect(290, 0, 911, 721))
        self.ui_layout_welcomePage.setContentsMargins(0, 0, 0, 0)
        self.ui_layout_welcomePage.setObjectName("ui_layout_welcomePage")
        self.ux_label_welcome = QtWidgets.QLabel(self.widget_welcomeLayout)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.ux_label_welcome.setFont(font)
        self.ux_label_welcome.setAlignment(QtCore.Qt.AlignCenter)
        self.ux_label_welcome.setObjectName("ux_label_welcome")
        self.ui_layout_welcomePage.addWidget(self.ux_label_welcome, 0, 0, 1, 1)

        # attach/set welcomePage layout to welcomePage widget
        self.widget_welcomeLayout.setLayout(self.ui_layout_welcomePage)
        self.stackedLayoutWidget.addWidget(self.widget_welcomeLayout)


    def ui_newOrder(self, stackedLayoutWidget):
        self.widget_newOrderLayout = QtWidgets.QWidget(stackedLayoutWidget)
        self.widget_newOrderLayout.setGeometry(QtCore.QRect(310, 20, 871, 681)) #110, 70, 1023, 721
        self.widget_newOrderLayout.setObjectName("gridLayoutWidget")
        self.ui_layout_newOrder = QtWidgets.QGridLayout()
        self.ui_layout_newOrder.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.ui_layout_newOrder.setSpacing(6)
        self.ui_layout_newOrder.setObjectName("ui_layout_newOrder")
        self.ux_pButton_revAndComp = QtWidgets.QPushButton(self.widget_newOrderLayout)
        self.ux_pButton_revAndComp.setMinimumSize(QtCore.QSize(0, 50))
        self.ux_pButton_revAndComp.setObjectName("ux_pButton_revAndComp")
        self.ui_layout_newOrder.addWidget(self.ux_pButton_revAndComp, 15, 4, 1, 1)
        self.ux_pButton_addProdToOrd = QtWidgets.QPushButton(self.widget_newOrderLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_pButton_addProdToOrd.sizePolicy().hasHeightForWidth())
        self.ux_pButton_addProdToOrd.setSizePolicy(sizePolicy)
        self.ux_pButton_addProdToOrd.setMinimumSize(QtCore.QSize(280, 0))
        self.ux_pButton_addProdToOrd.setObjectName("ux_pButton_addProdToOrd")
        self.ui_layout_newOrder.addWidget(self.ux_pButton_addProdToOrd, 13, 0, 1, 1)
        self.ux_tableWidget_curProducts = QtWidgets.QTableWidget(self.widget_newOrderLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_tableWidget_curProducts.sizePolicy().hasHeightForWidth())
        self.ux_tableWidget_curProducts.setSizePolicy(sizePolicy)
        self.ux_tableWidget_curProducts.setMinimumSize(QtCore.QSize(290, 0))
        self.ux_tableWidget_curProducts.setShowGrid(True)
        self.ux_tableWidget_curProducts.setRowCount(0)
        self.ux_tableWidget_curProducts.setColumnCount(2)
        self.ux_tableWidget_curProducts.setObjectName("ux_tableWidget_curProducts")
        item = QtWidgets.QTableWidgetItem()
        self.ux_tableWidget_curProducts.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ux_tableWidget_curProducts.setHorizontalHeaderItem(1, item)
        self.ux_tableWidget_curProducts.horizontalHeader().setCascadingSectionResizes(False)
        self.ux_tableWidget_curProducts.horizontalHeader().setDefaultSectionSize(140)
        self.ux_tableWidget_curProducts.verticalHeader().setVisible(False)
        self.ui_layout_newOrder.addWidget(self.ux_tableWidget_curProducts, 12, 0, 1, 1)
        self.ux_label_deliveryDate = QtWidgets.QLabel(self.widget_newOrderLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_label_deliveryDate.sizePolicy().hasHeightForWidth())
        self.ux_label_deliveryDate.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ux_label_deliveryDate.setFont(font)
        self.ux_label_deliveryDate.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.ux_label_deliveryDate.setObjectName("ux_label_deliveryDate")
        self.ui_layout_newOrder.addWidget(self.ux_label_deliveryDate, 4, 0, 1, 1)
        self.ux_label_clientName = QtWidgets.QLabel(self.widget_newOrderLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_label_clientName.sizePolicy().hasHeightForWidth())
        self.ux_label_clientName.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ux_label_clientName.setFont(font)
        self.ux_label_clientName.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.ux_label_clientName.setObjectName("ux_label_clientName")
        self.ui_layout_newOrder.addWidget(self.ux_label_clientName, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.ui_layout_newOrder.addItem(spacerItem, 5, 2, 1, 1)
        self.ux_label_orderNumber = QtWidgets.QLabel(self.widget_newOrderLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_label_orderNumber.sizePolicy().hasHeightForWidth())
        self.ux_label_orderNumber.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ux_label_orderNumber.setFont(font)
        self.ux_label_orderNumber.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.ux_label_orderNumber.setObjectName("ux_label_orderNumber")
        self.ui_layout_newOrder.addWidget(self.ux_label_orderNumber, 0, 0, 1, 1)
        self.ux_label_selectProd = QtWidgets.QLabel(self.widget_newOrderLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_label_selectProd.sizePolicy().hasHeightForWidth())
        self.ux_label_selectProd.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ux_label_selectProd.setFont(font)
        self.ux_label_selectProd.setAlignment(QtCore.Qt.AlignCenter)
        self.ux_label_selectProd.setObjectName("ux_label_selectProd")
        self.ui_layout_newOrder.addWidget(self.ux_label_selectProd, 11, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.ui_layout_newOrder.addItem(spacerItem1, 14, 4, 1, 1)
        self.ux_tableWidget_orderProducts = QtWidgets.QTableWidget(self.widget_newOrderLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_tableWidget_orderProducts.sizePolicy().hasHeightForWidth())
        self.ux_tableWidget_orderProducts.setSizePolicy(sizePolicy)
        self.ux_tableWidget_orderProducts.setShowGrid(True)
        self.ux_tableWidget_orderProducts.setRowCount(0)
        self.ux_tableWidget_orderProducts.setColumnCount(4)
        self.ux_tableWidget_orderProducts.setObjectName("ux_tableWidget_orderProducts")
        item = QtWidgets.QTableWidgetItem()
        self.ux_tableWidget_orderProducts.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ux_tableWidget_orderProducts.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ux_tableWidget_orderProducts.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ux_tableWidget_orderProducts.setHorizontalHeaderItem(3, item)
        self.ux_tableWidget_orderProducts.horizontalHeader().setDefaultSectionSize(120)
        self.ui_layout_newOrder.addWidget(self.ux_tableWidget_orderProducts, 12, 2, 1, 3)
        self.ux_label_prodInCurOrder = QtWidgets.QLabel(self.widget_newOrderLayout)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ux_label_prodInCurOrder.setFont(font)
        self.ux_label_prodInCurOrder.setAlignment(QtCore.Qt.AlignCenter)
        self.ux_label_prodInCurOrder.setObjectName("ux_label_prodInCurOrder")
        self.ui_layout_newOrder.addWidget(self.ux_label_prodInCurOrder, 11, 2, 1, 3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ui_layout_newOrder.addItem(spacerItem2, 12, 1, 1, 1)
        self.ux_lineEdit_deliveryDate = QtWidgets.QLineEdit(self.widget_newOrderLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_lineEdit_deliveryDate.sizePolicy().hasHeightForWidth())
        self.ux_lineEdit_deliveryDate.setSizePolicy(sizePolicy)
        self.ux_lineEdit_deliveryDate.setMinimumSize(QtCore.QSize(200, 0))
        self.ux_lineEdit_deliveryDate.setObjectName("ux_lineEdit_deliveryDate")
        self.ui_layout_newOrder.addWidget(self.ux_lineEdit_deliveryDate, 4, 1, 1, 2)
        self.ux_comboBox_clientName = QtWidgets.QComboBox(self.widget_newOrderLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_comboBox_clientName.sizePolicy().hasHeightForWidth())
        self.ux_comboBox_clientName.setSizePolicy(sizePolicy)
        self.ux_comboBox_clientName.setMinimumSize(QtCore.QSize(200, 0))
        self.ux_comboBox_clientName.setObjectName("ux_comboBox_clientName")
        self.ui_layout_newOrder.addWidget(self.ux_comboBox_clientName, 1, 1, 1, 2)
        self.ux_lineEdit_orderNumber = QtWidgets.QLineEdit(self.widget_newOrderLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_lineEdit_orderNumber.sizePolicy().hasHeightForWidth())
        self.ux_lineEdit_orderNumber.setSizePolicy(sizePolicy)
        self.ux_lineEdit_orderNumber.setMinimumSize(QtCore.QSize(200, 0))
        self.ux_lineEdit_orderNumber.setObjectName("ux_lineEdit_orderNumber")
        self.ui_layout_newOrder.addWidget(self.ux_lineEdit_orderNumber, 0, 1, 1, 2)
        self.ux_pButton_compOrder = QtWidgets.QPushButton(self.widget_newOrderLayout)
        self.ux_pButton_compOrder.setObjectName("ux_pButton_compOrder")
        self.ui_layout_newOrder.addWidget(self.ux_pButton_compOrder, 13, 2, 1, 3)

        self.widget_newOrderLayout.setLayout(self.ui_layout_newOrder)
        self.stackedLayoutWidget.addWidget(self.widget_newOrderLayout)

    def showLayout_newOrder(self):
        self.stackedLayoutWidget.setCurrentWidget(self.widget_newOrderLayout)