# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Views\view_main_ui_v2base.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
#
#   core concept credit for dynamic pages using QStacked objects: nathancy @ https://stackoverflow.com/a/55911336
#
#
#######################################################################################################


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QStandardItem, QStandardItemModel
from PyQt5.QtWidgets import QAbstractItemView



class Ui_MainWindow_mainView(object):

    # define model objects for listViews and other list containers
    model_listView_searchEditClients_nameSearchList = QStandardItemModel()
    model_listView_searchEditClients_NameIdList = []
    model_listView_newInvoice_nameSearchList = QStandardItemModel()
    model_listView_newInvoice_NameIdList = []


    def setupUi(self, main_view, model):

        # init main window
        main_view.setObjectName("main_view")
        main_view.resize(1200, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(main_view.sizePolicy().hasHeightForWidth())
        main_view.setSizePolicy(sizePolicy)
        main_view.setFixedSize(main_view.size())

        # init top-level QWidget in main window
        self.centralwidget = QtWidgets.QWidget(main_view)
        self.centralwidget.setObjectName("centralwidget")

        # init QWidget holding the left-most vertical layout
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, 0, 131, 721))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")

        # init left-most vertical layout (holds left buttons)
        self.ui_vLayout_viewMain = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.ui_vLayout_viewMain.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.ui_vLayout_viewMain.setContentsMargins(0, 0, 0, 0)
        self.ui_vLayout_viewMain.setSpacing(0)
        self.ui_vLayout_viewMain.setObjectName("ui_vLayout_viewMain")

        # init buttons within ui_vLayout_viewMain
        self.ux_pButton_orders = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_pButton_orders.sizePolicy().hasHeightForWidth())
        self.ux_pButton_orders.setSizePolicy(sizePolicy)
        self.ux_pButton_orders.setBaseSize(QtCore.QSize(0, 0))
        self.ux_pButton_orders.setObjectName("ux_pButton_orders")
        self.ui_vLayout_viewMain.addWidget(self.ux_pButton_orders)
        self.ux_pButton_clients = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_pButton_clients.sizePolicy().hasHeightForWidth())
        self.ux_pButton_clients.setSizePolicy(sizePolicy)
        self.ux_pButton_clients.setObjectName("ux_pButton_clients")
        self.ui_vLayout_viewMain.addWidget(self.ux_pButton_clients)
        self.ux_pButton_products = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_pButton_products.sizePolicy().hasHeightForWidth())
        self.ux_pButton_products.setSizePolicy(sizePolicy)
        self.ux_pButton_products.setObjectName("ux_pButton_products")
        self.ui_vLayout_viewMain.addWidget(self.ux_pButton_products)
        self.ux_pButton_invoicing = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_pButton_invoicing.sizePolicy().hasHeightForWidth())
        self.ux_pButton_invoicing.setSizePolicy(sizePolicy)
        self.ux_pButton_invoicing.setObjectName("ux_pButton_invoicing")
        self.ui_vLayout_viewMain.addWidget(self.ux_pButton_invoicing)
        self.ux_pButton_statistics = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_pButton_statistics.sizePolicy().hasHeightForWidth())
        self.ux_pButton_statistics.setSizePolicy(sizePolicy)
        self.ux_pButton_statistics.setObjectName("ux_pButton_statistics")
        self.ui_vLayout_viewMain.addWidget(self.ux_pButton_statistics)
        self.ux_pButton_settings = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_pButton_settings.sizePolicy().hasHeightForWidth())
        self.ux_pButton_settings.setSizePolicy(sizePolicy)
        self.ux_pButton_settings.setObjectName("ux_pButton_settings")
        self.ui_vLayout_viewMain.addWidget(self.ux_pButton_settings)

        # init 2nd level buttons (e.g. New Orders)
        self.ux_pButton_searchEditOrders = QtWidgets.QPushButton(self.centralwidget)
        self.ux_pButton_searchEditOrders.setGeometry(QtCore.QRect(130, 60, 161, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_pButton_searchEditOrders.sizePolicy().hasHeightForWidth())
        self.ux_pButton_searchEditOrders.setSizePolicy(sizePolicy)
        self.ux_pButton_searchEditOrders.setObjectName("ux_pButton_searchEditOrders")
        self.ux_pButton_newOrder = QtWidgets.QPushButton(self.centralwidget)
        self.ux_pButton_newOrder.setGeometry(QtCore.QRect(130, 0, 161, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_pButton_newOrder.sizePolicy().hasHeightForWidth())
        self.ux_pButton_newOrder.setSizePolicy(sizePolicy)
        self.ux_pButton_newOrder.setObjectName("ux_pButton_newOrder")
        self.ux_pButton_newClient = QtWidgets.QPushButton(self.centralwidget)
        self.ux_pButton_newClient.setGeometry(QtCore.QRect(130, 120, 161, 60))
        self.ux_pButton_newClient.setObjectName("ux_pButton_newClient")
        self.ux_pButton_editClient = QtWidgets.QPushButton(self.centralwidget)
        self.ux_pButton_editClient.setGeometry(QtCore.QRect(130, 180, 161, 60))
        self.ux_pButton_editClient.setObjectName("ux_pButton_editClient")
        self.ux_pButton_addProduct = QtWidgets.QPushButton(self.centralwidget)
        self.ux_pButton_addProduct.setGeometry(QtCore.QRect(130, 240, 161, 60))
        self.ux_pButton_addProduct.setObjectName("ux_pButton_addProduct")
        self.ux_pButton_editProduct = QtWidgets.QPushButton(self.centralwidget)
        self.ux_pButton_editProduct.setGeometry(QtCore.QRect(130, 300, 161, 60))
        self.ux_pButton_editProduct.setObjectName("ux_pButton_editProduct")
        self.ux_pButton_newInvoice = QtWidgets.QPushButton(self.centralwidget)
        self.ux_pButton_newInvoice.setGeometry(QtCore.QRect(130, 360, 161, 40))
        self.ux_pButton_newInvoice.setObjectName("ux_pButton_newInvoice")
        self.ux_pButton_sendInvoice = QtWidgets.QPushButton(self.centralwidget)
        self.ux_pButton_sendInvoice.setGeometry(QtCore.QRect(130, 400, 161, 40))
        self.ux_pButton_sendInvoice.setObjectName("ux_pButton_sendInvoice")
        self.ux_pButton_searchInvoice = QtWidgets.QPushButton(self.centralwidget)
        self.ux_pButton_searchInvoice.setGeometry(QtCore.QRect(130, 440, 161, 41))
        self.ux_pButton_searchInvoice.setObjectName("ux_pButton_searchInvoice")
        self.ux_pButton_summaryView = QtWidgets.QPushButton(self.centralwidget)
        self.ux_pButton_summaryView.setGeometry(QtCore.QRect(130, 481, 161, 60))
        self.ux_pButton_summaryView.setObjectName("ux_pButton_summaryView")
        self.ux_pButton_searchView = QtWidgets.QPushButton(self.centralwidget)
        self.ux_pButton_searchView.setGeometry(QtCore.QRect(130, 541, 161, 60))
        self.ux_pButton_searchView.setObjectName("ux_pButton_searchView")

        # init stacked layout widget; this is the top-level widget that holds the various
        #                               pages that change with button clicks
        self.stackedLayoutWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedLayoutWidget.setGeometry(QtCore.QRect(310, 20, 871, 681))
        self.stackedLayoutWidget.setObjectName("stackedLayoutWidget")

        # init all layout widgets to be displayed in the stackedLayoutWidget box
        self.ui_welcome(self.stackedLayoutWidget)
        self.ui_newOrder(self.stackedLayoutWidget)
        self.ui_newClient(self.stackedLayoutWidget)
        self.ui_searchEditClients(self.stackedLayoutWidget)
        self.ui_newProduct(self.stackedLayoutWidget)
        self.ui_newInvoice(self.stackedLayoutWidget)
        self.ui_newInvoiceCandS(self.stackedLayoutWidget, model)

        # set first shown widget (welcome)
        self.stackedLayoutWidget.setCurrentWidget(self.widget_welcomeLayout)

        main_view.setCentralWidget(self.centralwidget)

        self.retranslateUi(main_view)
        QtCore.QMetaObject.connectSlotsByName(main_view)

    def retranslateUi(self, MainWindow_mainView):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_mainView.setWindowTitle(_translate("main_view", "MainWindow"))

        # leftmost pButtons
        self.ux_pButton_orders.setText(_translate("main_view", "Orders"))
        self.ux_pButton_clients.setText(_translate("main_view", "Clients"))
        self.ux_pButton_products.setText(_translate("main_view", "Products"))
        self.ux_pButton_invoicing.setText(_translate("main_view", "Invoicing"))
        self.ux_pButton_statistics.setText(_translate("main_view", "Statistics"))
        self.ux_pButton_settings.setText(_translate("main_view", "Settings"))

        # 2nd level/tier buttons (buttons to the right of the leftmost buttons
        self.ux_pButton_newOrder.setText(_translate("main_view", "New Order"))
        self.ux_pButton_searchEditOrders.setText(_translate("main_view", "Search/Edit Orders"))
        self.ux_pButton_newClient.setText(_translate("main_view", "Add New Client"))
        self.ux_pButton_editClient.setText(_translate("main_view", "Search/Edit Client Info."))
        self.ux_pButton_addProduct.setText(_translate("main_view", "Add New Product"))
        self.ux_pButton_editProduct.setText(_translate("main_view", "Search/Edit Product Info."))
        self.ux_pButton_newInvoice.setText(_translate("main_view", "Create New Invoice"))
        self.ux_pButton_sendInvoice.setText(_translate("main_view", "Send Invoice(s)"))
        self.ux_pButton_searchInvoice.setText(_translate("main_view", "Search Invoices"))
        self.ux_pButton_summaryView.setText(_translate("main_view", "Summary View"))
        self.ux_pButton_searchView.setText(_translate("main_view", "Search and View"))

        # translate for Welcome page in main_view
        self.ux_label_welcome.setText(_translate("main_view", "Welcome!"))

        # add new order page
        self.ux_label_clientName.setText(_translate("main_view", "Client Name:"))
        self.ux_label_deliveryDate.setText(_translate("main_view", "Delivery Date:"))
        self.ux_label_orderNumber.setText(_translate("main_view", "Facture/Order #:"))
        self.ux_label_prodInCurOrder.setText(_translate("main_view", "Products in Current Order:"))
        item = self.ux_tableWidget_curProducts.horizontalHeaderItem(0)
        item.setText(_translate("main_view", "Product Name"))
        item = self.ux_tableWidget_curProducts.horizontalHeaderItem(1)
        item.setText(_translate("main_view", "Price-Per-Unit"))
        item = self.ux_tableWidget_orderProducts.horizontalHeaderItem(0)
        item.setText(_translate("main_view", "Product Name"))
        item = self.ux_tableWidget_orderProducts.horizontalHeaderItem(1)
        item.setText(_translate("main_view", "Unit Amount"))
        item = self.ux_tableWidget_orderProducts.horizontalHeaderItem(2)
        item.setText(_translate("main_view", "Price-Per-Unit"))
        item = self.ux_tableWidget_orderProducts.horizontalHeaderItem(3)
        item.setText(_translate("main_view", "Total Cost"))
        self.ux_pButton_compOrder.setText(_translate("main_view", "Remove Product From Order"))
        self.ux_pButton_revAndComp.setText(_translate("main_view", "Review and Complete Order"))
        self.ux_pButton_addProdToOrd.setText(_translate("main_view", "Add Product To Order"))
        self.ux_label_selectProd.setText(_translate("main_view", "Select Products for Current Order:"))

        # Add new client page
        self.ux_label_newClientAddress_line2.setText(_translate("main_view", "Client City Code and City:"))
        self.ux_pButton_addClient.setText(_translate("main_view", "Add New Client"))
        self.ux_label_newClientPhone.setText(_translate("main_view", "Client Phone Number:"))
        self.ux_label_newClientName.setText(_translate("main_view", "Client Name:"))
        self.ux_label_newClientAddress_line1.setText(_translate("main_view", "Client Street Address:"))
        self.ui_label_addNewClientHeader.setText(_translate("main_view", "Add New Client"))
        self.ux_label_newClientEmail.setText(_translate("main_view", "Client Email Address:"))
        self.ux_pButton_newClient.setText(_translate("main_view", "Add New Client"))

        # # retranslateUI for searchEditClient page
        self.ui_label_searchEditClients_header.setText(
            _translate("main_view", "Search/Edit Client Information"))
        self.ui_label_searchEditClients_typeBelow.setText(
            _translate("main_view", "Type a Clent Name Below to Search:"))
        self.ui_label_searchEditClients_clientEmail.setText(_translate("main_view", "Client Email:"))
        self.ui_label_searchEditClients_doubleClickTo.setText(
            _translate("main_view", "Double-Click on Client Name Below to Show Information:"))
        self.ui_label_searchEditClients_clientName.setText(_translate("main_view", "Client Name:"))
        self.ui_label_searchEditClients_addressLine2.setText(
            _translate("main_view", "Client Address Line 2:"))
        self.ui_label_searchEditClients_addressLine1.setText(
            _translate("main_view", "Client Address Line 1:"))
        self.ui_label_searchEditClients_clientPhone.setText(_translate("main_view", "Client Phone:"))
        self.ux_pButton_searchEditClients_editClientInfo.setText(
            _translate("main_view", "Edit Client Information"))
        self.ux_pButton_searchEditClients_finalizeInfo.setText(
            _translate("main_view", "Finalize Information Edit"))

        # retranslateUi() for newProduct page
        self.ux_label_newProduct_price.setText(_translate("main_view", "Product Price-Per-Unit:"))
        self.ux_label_newProduct_name.setText(_translate("main_view", "Product Name:"))
        self.ux_label_newProduct_description.setText(_translate("main_view", "Product Description:"))
        self.ux_pButton_newProduct_addProd.setText(_translate("main_view", "Add New Product To Database"))
        self.ui_label_newProduct_header.setText(_translate("main_view", "Add New Products"))

        # retranslateUi() for newInvoice page
        self.ui_label_newInvoice_orderNumber.setText(_translate("main_view", "Order Number:"))
        self.ui_label_newInvoice_orderSubTotal.setText(_translate("main_view", "Order SubTotal:"))
        self.ui_label_newInvoice_doubleClickTo_2.setText(
            _translate("main_view", "Double-Click on an Order Number to Show Orders Details:"))
        self.ui_label_newInvoice_doubleClickTo.setText(
            _translate("main_view", "Double-Click on Client Name Below to Show Client Orders:"))
        self.ui_label_newInvoice_clientEmail.setText(_translate("main_view", "Client Email:"))
        self.ui_label_newInvoice_addressLine1.setText(_translate("main_view", "Client Address Line 1:"))
        self.ui_label_newInvoice_addressLine2.setText(_translate("main_view", "Client Address Line 2:"))
        self.ui_label_newInvoice_typeBelow.setText(
            _translate("main_view", "Type a Client Name Below to Search:"))
        self.ui_label_newInvoice_header.setText(_translate("main_view", "Create New Invoice"))
        self.ux_pButton_newInvoice_showAllOrders.setText(_translate("main_view", "Show All Orders"))
        self.ui_label_newInvoice_clientPhone.setText(_translate("main_view", "Client Phone:"))
        self.ui_label_newInvoice_taxApplied.setText(_translate("main_view", "Tax Applied (in %):"))
        self.ui_label_newInvoice_orderTotal.setText(_translate("main_view", "Order Total:"))
        self.ui_label_newInvoice_clientName.setText(_translate("main_view", "Client Name:"))
        self.ui_label_newInvoice_orderItems.setText(_translate("main_view", "Order Items:"))
        self.ux_pButton_newInvoice_ShowUnpaidOrders.setText(_translate("main_view", "Show Unpaid Orders"))
        self.ux_pButton_newInvoice_createInvoice.setText(_translate("main_view", "Create Invoice"))
        self.ux_pButton_newInvoice_createAndSendInvoice.setText(
            _translate("main_view", "Create And Send Invoice"))

        # newInvoiceCandS page
        self.ui_label_newInvoiceCandS_orderSubTotal.setText(_translate("main_view", "Order SubTotal:"))
        self.ui_label_newInvoiceCandS_addressLine1.setText(_translate("main_view", "Client Address Line 1:"))
        self.ui_label_newInvoiceCandS_clientEmail.setText(_translate("main_view", "Client Email:"))
        self.ui_label_newInvoiceCandS_addressLine2.setText(_translate("main_view", "Client Address Line 2:"))
        self.ui_label_newInvoiceCandS_header.setText(_translate("main_view", "Create and Send New Invoice"))
        self.ux_pButton_newInvoiceCandS_showAllOrders.setText(_translate("main_view", "Show All Orders"))
        self.ui_label_newInvoiceCandS_clientPhone.setText(_translate("main_view", "Client Phone:"))
        self.ui_label_newInvoiceCandS_orderTotal.setText(_translate("main_view", "Order Total:"))
        self.ui_label_newInvoiceCandS_taxApplied.setText(_translate("main_view", "Tax Applied (in %):"))
        self.ui_label_newInvoiceCandS_clientName.setText(_translate("main_view", "Client Name:"))
        self.ui_label_newInvoiceCandS_orderItems.setText(_translate("main_view", "Order Items:"))
        self.ux_pButton_newInvoiceCandS_ShowUnsentOrders.setText(
            _translate("main_view", "Show Orders without Invoices Sent"))
        self.ui_label_newInvoiceCandS_doubleClickTo.setText(
            _translate("main_view", "Double-Click on an Order Number to Show Orders Details:"))
        self.ui_label_newInvoiceCandS_clickBelowToSend.setText(
            _translate("main_view", "Click Below to Bring-Up your Default Email Client with"))
        self.ui_label_newInvoiceCandS_orderNumber.setText(_translate("main_view", "Order Number:"))
        self.ux_pButton_newInvoiceCandS_createAndSendInvoice.setText(
            _translate("main_view", "Create And Send Invoice"))

    ############################################################
    #
    #   ui_welcome - initial window on startup of MainWindow
    #
    ############################################################
    def ui_welcome(self, stackedLayoutWidget):
        # init welcome window widget; widget that represents the welcome window (first window)
        self.widget_welcomeLayout = QtWidgets.QWidget(stackedLayoutWidget)
        self.widget_welcomeLayout.setGeometry(QtCore.QRect(290, 0, 911, 721))
        self.widget_welcomeLayout.setObjectName("welcomeLayoutWidget")

        # init layout for welcome window
        self.ui_layout_welcomePage = QtWidgets.QGridLayout(self.widget_welcomeLayout)
        self.ui_layout_welcomePage.setGeometry(QtCore.QRect(290, 0, 911, 721))
        self.ui_layout_welcomePage.setContentsMargins(0, 0, 0, 0)
        self.ui_layout_welcomePage.setObjectName("ui_layout_welcomePage")
        self.ux_label_welcome = QtWidgets.QLabel(self.widget_welcomeLayout)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.ux_label_welcome.setFont(font)
        self.ux_label_welcome.setAlignment(QtCore.Qt.AlignCenter)
        self.ux_label_welcome.setObjectName("ux_label_welcome")
        self.ui_layout_welcomePage.addWidget(self.ux_label_welcome, 0, 0, 1, 1)

        # attach/set welcomePage layout to welcomePage widget
        self.widget_welcomeLayout.setLayout(self.ui_layout_welcomePage)
        self.stackedLayoutWidget.addWidget(self.widget_welcomeLayout)

    ############################################################
    #
    #   ui_newOrder - window layout shown after "New Order" button click
    #
    ############################################################
    def ui_newOrder(self, stackedLayoutWidget):
        self.widget_newOrderLayout = QtWidgets.QWidget(stackedLayoutWidget)
        self.widget_newOrderLayout.setGeometry(QtCore.QRect(310, 20, 871, 681)) #110, 70, 1023, 721
        self.widget_newOrderLayout.setObjectName("widget_newOrderLayout")
        self.ui_layout_newOrder = QtWidgets.QGridLayout()
        self.ui_layout_newOrder.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.ui_layout_newOrder.setSpacing(6)
        self.ui_layout_newOrder.setObjectName("ui_layout_newOrder")
        self.ux_pButton_revAndComp = QtWidgets.QPushButton(self.widget_newOrderLayout)
        self.ux_pButton_revAndComp.setMinimumSize(QtCore.QSize(0, 50))
        self.ux_pButton_revAndComp.setObjectName("ux_pButton_revAndComp")
        self.ui_layout_newOrder.addWidget(self.ux_pButton_revAndComp, 15, 4, 1, 1)
        self.ux_pButton_addProdToOrd = QtWidgets.QPushButton(self.widget_newOrderLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_pButton_addProdToOrd.sizePolicy().hasHeightForWidth())
        self.ux_pButton_addProdToOrd.setSizePolicy(sizePolicy)
        self.ux_pButton_addProdToOrd.setMinimumSize(QtCore.QSize(280, 0))
        self.ux_pButton_addProdToOrd.setObjectName("ux_pButton_addProdToOrd")
        self.ui_layout_newOrder.addWidget(self.ux_pButton_addProdToOrd, 13, 0, 1, 1)
        self.ux_tableWidget_curProducts = QtWidgets.QTableWidget(self.widget_newOrderLayout)
        self.ux_tableWidget_curProducts.setSelectionMode(QAbstractItemView.SingleSelection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_tableWidget_curProducts.sizePolicy().hasHeightForWidth())
        self.ux_tableWidget_curProducts.setSizePolicy(sizePolicy)
        self.ux_tableWidget_curProducts.setMinimumSize(QtCore.QSize(290, 0))
        self.ux_tableWidget_curProducts.setShowGrid(True)
        self.ux_tableWidget_curProducts.setRowCount(0)
        self.ux_tableWidget_curProducts.setColumnCount(2)
        self.ux_tableWidget_curProducts.setObjectName("ux_tableWidget_curProducts")
        item = QtWidgets.QTableWidgetItem()
        self.ux_tableWidget_curProducts.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ux_tableWidget_curProducts.setHorizontalHeaderItem(1, item)
        self.ux_tableWidget_curProducts.horizontalHeader().setCascadingSectionResizes(False)
        self.ux_tableWidget_curProducts.horizontalHeader().setDefaultSectionSize(140)
        self.ux_tableWidget_curProducts.verticalHeader().setVisible(False)
        self.ui_layout_newOrder.addWidget(self.ux_tableWidget_curProducts, 12, 0, 1, 1)
        self.ux_label_deliveryDate = QtWidgets.QLabel(self.widget_newOrderLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_label_deliveryDate.sizePolicy().hasHeightForWidth())
        self.ux_label_deliveryDate.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ux_label_deliveryDate.setFont(font)
        self.ux_label_deliveryDate.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.ux_label_deliveryDate.setObjectName("ux_label_deliveryDate")
        self.ui_layout_newOrder.addWidget(self.ux_label_deliveryDate, 4, 0, 1, 1)
        self.ux_label_clientName = QtWidgets.QLabel(self.widget_newOrderLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_label_clientName.sizePolicy().hasHeightForWidth())
        self.ux_label_clientName.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ux_label_clientName.setFont(font)
        self.ux_label_clientName.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.ux_label_clientName.setObjectName("ux_label_clientName")
        self.ui_layout_newOrder.addWidget(self.ux_label_clientName, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.ui_layout_newOrder.addItem(spacerItem, 5, 2, 1, 1)
        self.ux_label_orderNumber = QtWidgets.QLabel(self.widget_newOrderLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_label_orderNumber.sizePolicy().hasHeightForWidth())
        self.ux_label_orderNumber.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ux_label_orderNumber.setFont(font)
        self.ux_label_orderNumber.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.ux_label_orderNumber.setObjectName("ux_label_orderNumber")
        self.ui_layout_newOrder.addWidget(self.ux_label_orderNumber, 0, 0, 1, 1)
        self.ux_label_selectProd = QtWidgets.QLabel(self.widget_newOrderLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_label_selectProd.sizePolicy().hasHeightForWidth())
        self.ux_label_selectProd.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ux_label_selectProd.setFont(font)
        self.ux_label_selectProd.setAlignment(QtCore.Qt.AlignCenter)
        self.ux_label_selectProd.setObjectName("ux_label_selectProd")
        self.ui_layout_newOrder.addWidget(self.ux_label_selectProd, 11, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.ui_layout_newOrder.addItem(spacerItem1, 14, 4, 1, 1)
        self.ux_tableWidget_orderProducts = QtWidgets.QTableWidget(self.widget_newOrderLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_tableWidget_orderProducts.sizePolicy().hasHeightForWidth())
        self.ux_tableWidget_orderProducts.setSelectionMode(QAbstractItemView.SingleSelection)
        self.ux_tableWidget_orderProducts.setSizePolicy(sizePolicy)
        self.ux_tableWidget_orderProducts.setShowGrid(True)
        self.ux_tableWidget_orderProducts.setRowCount(0)
        self.ux_tableWidget_orderProducts.setColumnCount(4)
        self.ux_tableWidget_orderProducts.setObjectName("ux_tableWidget_orderProducts")
        item = QtWidgets.QTableWidgetItem()
        self.ux_tableWidget_orderProducts.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ux_tableWidget_orderProducts.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ux_tableWidget_orderProducts.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ux_tableWidget_orderProducts.setHorizontalHeaderItem(3, item)
        self.ux_tableWidget_orderProducts.horizontalHeader().setDefaultSectionSize(120)
        self.ui_layout_newOrder.addWidget(self.ux_tableWidget_orderProducts, 12, 2, 1, 3)
        self.ux_label_prodInCurOrder = QtWidgets.QLabel(self.widget_newOrderLayout)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ux_label_prodInCurOrder.setFont(font)
        self.ux_label_prodInCurOrder.setAlignment(QtCore.Qt.AlignCenter)
        self.ux_label_prodInCurOrder.setObjectName("ux_label_prodInCurOrder")
        self.ui_layout_newOrder.addWidget(self.ux_label_prodInCurOrder, 11, 2, 1, 3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ui_layout_newOrder.addItem(spacerItem2, 12, 1, 1, 1)
        self.ux_lineEdit_deliveryDate = QtWidgets.QLineEdit(self.widget_newOrderLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_lineEdit_deliveryDate.sizePolicy().hasHeightForWidth())
        self.ux_lineEdit_deliveryDate.setSizePolicy(sizePolicy)
        self.ux_lineEdit_deliveryDate.setMinimumSize(QtCore.QSize(200, 0))
        self.ux_lineEdit_deliveryDate.setObjectName("ux_lineEdit_deliveryDate")
        self.ui_layout_newOrder.addWidget(self.ux_lineEdit_deliveryDate, 4, 1, 1, 2)
        self.ux_comboBox_clientName = QtWidgets.QComboBox(self.widget_newOrderLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_comboBox_clientName.sizePolicy().hasHeightForWidth())
        self.ux_comboBox_clientName.setSizePolicy(sizePolicy)
        self.ux_comboBox_clientName.setMinimumSize(QtCore.QSize(200, 0))
        self.ux_comboBox_clientName.setObjectName("ux_comboBox_clientName")
        self.ui_layout_newOrder.addWidget(self.ux_comboBox_clientName, 1, 1, 1, 2)
        self.ux_lineEdit_orderNumber = QtWidgets.QLineEdit(self.widget_newOrderLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_lineEdit_orderNumber.sizePolicy().hasHeightForWidth())
        self.ux_lineEdit_orderNumber.setSizePolicy(sizePolicy)
        self.ux_lineEdit_orderNumber.setMinimumSize(QtCore.QSize(200, 0))
        self.ux_lineEdit_orderNumber.setObjectName("ux_lineEdit_orderNumber")
        self.ui_layout_newOrder.addWidget(self.ux_lineEdit_orderNumber, 0, 1, 1, 2)
        self.ux_pButton_compOrder = QtWidgets.QPushButton(self.widget_newOrderLayout)
        self.ux_pButton_compOrder.setObjectName("ux_pButton_compOrder")
        self.ui_layout_newOrder.addWidget(self.ux_pButton_compOrder, 13, 2, 1, 3)

        self.widget_newOrderLayout.setLayout(self.ui_layout_newOrder)
        self.stackedLayoutWidget.addWidget(self.widget_newOrderLayout)

    def showLayout_newOrder(self):
        self.stackedLayoutWidget.setCurrentWidget(self.widget_newOrderLayout)

    ############################################################
    #
    #   ui_newClient - initial window on startup of MainWindow
    #
    ############################################################
    def ui_newClient(self, stackedLayoutWidget):
        self.widget_newClientLayout = QtWidgets.QWidget(stackedLayoutWidget)
        self.widget_newClientLayout.setGeometry(QtCore.QRect(310, 20, 871, 681))
        self.widget_newClientLayout.setObjectName("widget_newClientLayout")
        self.ui_layout_newClientPage = QtWidgets.QGridLayout()
        self.ui_layout_newClientPage.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.ui_layout_newClientPage.setSpacing(6)
        self.ui_layout_newClientPage.setObjectName("ui_layout_newClientPage")
        self.ux_lineEdit_newClientName = QtWidgets.QLineEdit(self.widget_newClientLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_lineEdit_newClientName.sizePolicy().hasHeightForWidth())
        self.ux_lineEdit_newClientName.setSizePolicy(sizePolicy)
        self.ux_lineEdit_newClientName.setMinimumSize(QtCore.QSize(200, 0))
        self.ux_lineEdit_newClientName.setObjectName("ux_lineEdit_newClientName")
        self.ui_layout_newClientPage.addWidget(self.ux_lineEdit_newClientName, 2, 1, 1, 2)
        self.ux_label_newClientAddress_line2 = QtWidgets.QLabel(self.widget_newClientLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_label_newClientAddress_line2.sizePolicy().hasHeightForWidth())
        self.ux_label_newClientAddress_line2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ux_label_newClientAddress_line2.setFont(font)
        self.ux_label_newClientAddress_line2.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.ux_label_newClientAddress_line2.setObjectName("ux_label_newClientAddress_line2")
        self.ui_layout_newClientPage.addWidget(self.ux_label_newClientAddress_line2, 6, 0, 1, 1)
        self.ux_lineEdit_addressLine1 = QtWidgets.QLineEdit(self.widget_newClientLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_lineEdit_addressLine1.sizePolicy().hasHeightForWidth())
        self.ux_lineEdit_addressLine1.setSizePolicy(sizePolicy)
        self.ux_lineEdit_addressLine1.setMinimumSize(QtCore.QSize(200, 0))
        self.ux_lineEdit_addressLine1.setObjectName("ux_lineEdit_addressLine1")
        self.ui_layout_newClientPage.addWidget(self.ux_lineEdit_addressLine1, 5, 1, 1, 2)
        self.ux_pButton_addClient = QtWidgets.QPushButton(self.widget_newClientLayout)
        self.ux_pButton_addClient.setMinimumSize(QtCore.QSize(0, 50))
        self.ux_pButton_addClient.setObjectName("ux_pButton_addClient")
        self.ui_layout_newClientPage.addWidget(self.ux_pButton_addClient, 13, 3, 1, 1)
        self.ux_lineEdit_addressLine2 = QtWidgets.QLineEdit(self.widget_newClientLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_lineEdit_addressLine2.sizePolicy().hasHeightForWidth())
        self.ux_lineEdit_addressLine2.setSizePolicy(sizePolicy)
        self.ux_lineEdit_addressLine2.setMinimumSize(QtCore.QSize(200, 0))
        self.ux_lineEdit_addressLine2.setObjectName("ux_lineEdit_addressLine2")
        self.ui_layout_newClientPage.addWidget(self.ux_lineEdit_addressLine2, 6, 1, 1, 2)
        self.ux_label_newClientPhone = QtWidgets.QLabel(self.widget_newClientLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_label_newClientPhone.sizePolicy().hasHeightForWidth())
        self.ux_label_newClientPhone.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ux_label_newClientPhone.setFont(font)
        self.ux_label_newClientPhone.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.ux_label_newClientPhone.setObjectName("ux_label_newClientPhone")
        self.ui_layout_newClientPage.addWidget(self.ux_label_newClientPhone, 7, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.ui_layout_newClientPage.addItem(spacerItem, 1, 1, 1, 2)
        self.ux_label_newClientName = QtWidgets.QLabel(self.widget_newClientLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_label_newClientName.sizePolicy().hasHeightForWidth())
        self.ux_label_newClientName.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ux_label_newClientName.setFont(font)
        self.ux_label_newClientName.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.ux_label_newClientName.setObjectName("ux_label_newClientName")
        self.ui_layout_newClientPage.addWidget(self.ux_label_newClientName, 2, 0, 1, 1)
        self.ux_label_newClientAddress_line1 = QtWidgets.QLabel(self.widget_newClientLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_label_newClientAddress_line1.sizePolicy().hasHeightForWidth())
        self.ux_label_newClientAddress_line1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ux_label_newClientAddress_line1.setFont(font)
        self.ux_label_newClientAddress_line1.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.ux_label_newClientAddress_line1.setObjectName("ux_label_newClientAddress_line1")
        self.ui_layout_newClientPage.addWidget(self.ux_label_newClientAddress_line1, 5, 0, 1, 1)
        self.ux_lineEdit_newClientPhone = QtWidgets.QLineEdit(self.widget_newClientLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_lineEdit_newClientPhone.sizePolicy().hasHeightForWidth())
        self.ux_lineEdit_newClientPhone.setSizePolicy(sizePolicy)
        self.ux_lineEdit_newClientPhone.setMinimumSize(QtCore.QSize(200, 0))
        self.ux_lineEdit_newClientPhone.setObjectName("ux_lineEdit_newClientPhone")
        self.ui_layout_newClientPage.addWidget(self.ux_lineEdit_newClientPhone, 7, 1, 1, 2)
        self.ui_label_addNewClientHeader = QtWidgets.QLabel(self.widget_newClientLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_label_addNewClientHeader.sizePolicy().hasHeightForWidth())
        self.ui_label_addNewClientHeader.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.ui_label_addNewClientHeader.setFont(font)
        self.ui_label_addNewClientHeader.setAlignment(QtCore.Qt.AlignCenter)
        self.ui_label_addNewClientHeader.setObjectName("ui_label_addNewClientHeader")
        self.ui_layout_newClientPage.addWidget(self.ui_label_addNewClientHeader, 0, 0, 1, 4)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ui_layout_newClientPage.addItem(spacerItem1, 12, 1, 1, 1)
        self.ux_label_newClientEmail = QtWidgets.QLabel(self.widget_newClientLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_label_newClientEmail.sizePolicy().hasHeightForWidth())
        self.ux_label_newClientEmail.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ux_label_newClientEmail.setFont(font)
        self.ux_label_newClientEmail.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.ux_label_newClientEmail.setObjectName("ux_label_newClientEmail")
        self.ui_layout_newClientPage.addWidget(self.ux_label_newClientEmail, 8, 0, 1, 1)
        self.ux_lineEdit_newClientEmail = QtWidgets.QLineEdit(self.widget_newClientLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_lineEdit_newClientEmail.sizePolicy().hasHeightForWidth())
        self.ux_lineEdit_newClientEmail.setSizePolicy(sizePolicy)
        self.ux_lineEdit_newClientEmail.setMinimumSize(QtCore.QSize(200, 0))
        self.ux_lineEdit_newClientEmail.setObjectName("ux_lineEdit_newClientEmail")
        self.ui_layout_newClientPage.addWidget(self.ux_lineEdit_newClientEmail, 8, 1, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.ui_layout_newClientPage.addItem(spacerItem2, 13, 2, 1, 1)
        #self.ui_layout_newClientPage.addLayout(self.ui_layout_newClientPage, 0, 0, 1, 1)

        # attach/set newClient layout to welcomePage widget
        self.widget_newClientLayout.setLayout(self.ui_layout_newClientPage)
        self.stackedLayoutWidget.addWidget(self.widget_newClientLayout)

    ####################################################################################################################
    #
    #   ui_searchEditClients - window layout shown after "Search/Edit Client Info" button click
    #
    ####################################################################################################################
    def ui_searchEditClients(self, stackedLayoutWidget):
        self.widget_searchEditClientsLayout = QtWidgets.QWidget(stackedLayoutWidget)
        self.widget_searchEditClientsLayout.setGeometry(QtCore.QRect(310, 20, 871, 681))
        self.widget_searchEditClientsLayout.setObjectName("widget_searchEditClientsLayout")
        self.ui_layout_searchEditClients = QtWidgets.QGridLayout()
        self.ui_layout_searchEditClients.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.ui_layout_searchEditClients.setSpacing(6)
        self.ui_layout_searchEditClients.setObjectName("ui_layout_searchEditClients")
        self.ui_ListView_searchEditClients_nameSearchList = QtWidgets.QListView(self.widget_searchEditClientsLayout)
        self.ui_ListView_searchEditClients_nameSearchList.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.ui_ListView_searchEditClients_nameSearchList.setObjectName(
            "ui_ListView_searchEditClients_nameSearchList")

        # set model for listView containing client names
        self.ui_ListView_searchEditClients_nameSearchList.setModel(self.model_listView_searchEditClients_nameSearchList)

        self.ui_layout_searchEditClients.addWidget(self.ui_ListView_searchEditClients_nameSearchList, 8, 1, 7, 1)
        self.ui_label_searchEditClients_header = QtWidgets.QLabel(self.widget_searchEditClientsLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_label_searchEditClients_header.sizePolicy().hasHeightForWidth())
        self.ui_label_searchEditClients_header.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.ui_label_searchEditClients_header.setFont(font)
        self.ui_label_searchEditClients_header.setAlignment(QtCore.Qt.AlignCenter)
        self.ui_label_searchEditClients_header.setObjectName("ui_label_searchEditClients_header")
        self.ui_layout_searchEditClients.addWidget(self.ui_label_searchEditClients_header, 0, 1, 1, 5)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.ui_layout_searchEditClients.addItem(spacerItem, 13, 5, 1, 1)
        self.ui_label_searchEditClients_typeBelow = QtWidgets.QLabel(self.widget_searchEditClientsLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_label_searchEditClients_typeBelow.sizePolicy().hasHeightForWidth())
        self.ui_label_searchEditClients_typeBelow.setSizePolicy(sizePolicy)
        self.ui_label_searchEditClients_typeBelow.setObjectName("ui_label_searchEditClients_typeBelow")
        self.ui_layout_searchEditClients.addWidget(self.ui_label_searchEditClients_typeBelow, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ui_layout_searchEditClients.addItem(spacerItem1, 8, 6, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.ui_layout_searchEditClients.addItem(spacerItem2, 1, 2, 1, 1)
        self.ui_label_searchEditClients_clientEmail = QtWidgets.QLabel(self.widget_searchEditClientsLayout)
        self.ui_label_searchEditClients_clientEmail.setObjectName("ui_label_searchEditClients_clientEmail")
        self.ui_layout_searchEditClients.addWidget(self.ui_label_searchEditClients_clientEmail, 12, 3, 1, 1)
        self.ui_label_searchEditClients_doubleClickTo = QtWidgets.QLabel(self.widget_searchEditClientsLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_label_searchEditClients_doubleClickTo.sizePolicy().hasHeightForWidth())
        self.ui_label_searchEditClients_doubleClickTo.setSizePolicy(sizePolicy)
        self.ui_label_searchEditClients_doubleClickTo.setObjectName("ui_label_searchEditClients_doubleClickTo")
        self.ui_layout_searchEditClients.addWidget(self.ui_label_searchEditClients_doubleClickTo, 5, 1, 1, 1)
        self.ux_lineEdit_searchEditClients_clientNameSearch = QtWidgets.QLineEdit(self.widget_searchEditClientsLayout)
        self.ux_lineEdit_searchEditClients_clientNameSearch.setObjectName(
            "ux_lineEdit_searchEditClients_clientNameSearch")
        self.ui_layout_searchEditClients.addWidget(self.ux_lineEdit_searchEditClients_clientNameSearch, 3, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ui_layout_searchEditClients.addItem(spacerItem3, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.ui_layout_searchEditClients.addItem(spacerItem4, 15, 1, 2, 1)
        self.ui_label_searchEditClients_clientName = QtWidgets.QLabel(self.widget_searchEditClientsLayout)
        self.ui_label_searchEditClients_clientName.setObjectName("ui_label_searchEditClients_clientName")
        self.ui_layout_searchEditClients.addWidget(self.ui_label_searchEditClients_clientName, 8, 3, 1, 1)
        self.ui_label_searchEditClients_addressLine2 = QtWidgets.QLabel(self.widget_searchEditClientsLayout)
        self.ui_label_searchEditClients_addressLine2.setObjectName("ui_label_searchEditClients_addressLine2")
        self.ui_layout_searchEditClients.addWidget(self.ui_label_searchEditClients_addressLine2, 10, 3, 1, 1)
        self.ui_label_searchEditClients_addressLine1 = QtWidgets.QLabel(self.widget_searchEditClientsLayout)
        self.ui_label_searchEditClients_addressLine1.setObjectName("ui_label_searchEditClients_addressLine1")
        self.ui_layout_searchEditClients.addWidget(self.ui_label_searchEditClients_addressLine1, 9, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ui_layout_searchEditClients.addItem(spacerItem5, 3, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ui_layout_searchEditClients.addItem(spacerItem6, 8, 4, 1, 1)
        self.ui_label_searchEditClients_clientPhone = QtWidgets.QLabel(self.widget_searchEditClientsLayout)
        self.ui_label_searchEditClients_clientPhone.setObjectName("ui_label_searchEditClients_clientPhone")
        self.ui_layout_searchEditClients.addWidget(self.ui_label_searchEditClients_clientPhone, 11, 3, 1, 1)
        self.ux_pButton_searchEditClients_editClientInfo = QtWidgets.QPushButton(self.widget_searchEditClientsLayout)
        self.ux_pButton_searchEditClients_editClientInfo.setObjectName(
            "ux_pButton_searchEditClients_editClientInfo")
        self.ui_layout_searchEditClients.addWidget(self.ux_pButton_searchEditClients_editClientInfo, 14, 3, 1, 1)
        self.ux_lineEdit_searchEditClients_cNameOut = QtWidgets.QLineEdit(self.widget_searchEditClientsLayout)
        self.ux_lineEdit_searchEditClients_cNameOut.setObjectName("ux_lineEdit_searchEditClients_cNameOut")
        self.ui_layout_searchEditClients.addWidget(self.ux_lineEdit_searchEditClients_cNameOut, 8, 5, 1, 1)
        self.ux_lineEdit_searchEditClients_address1Out = QtWidgets.QLineEdit(self.widget_searchEditClientsLayout)
        self.ux_lineEdit_searchEditClients_address1Out.setObjectName("ux_lineEdit_searchEditClients_address1Out")
        self.ui_layout_searchEditClients.addWidget(self.ux_lineEdit_searchEditClients_address1Out, 9, 5, 1, 1)
        self.ux_lineEdit_searchEditClients_address2Out = QtWidgets.QLineEdit(self.widget_searchEditClientsLayout)
        self.ux_lineEdit_searchEditClients_address2Out.setObjectName("ux_lineEdit_searchEditClients_address2Out")
        self.ui_layout_searchEditClients.addWidget(self.ux_lineEdit_searchEditClients_address2Out, 10, 5, 1, 1)
        self.ux_lineEdit_searchEditClients_cPhoneOut = QtWidgets.QLineEdit(self.widget_searchEditClientsLayout)
        self.ux_lineEdit_searchEditClients_cPhoneOut.setObjectName("ux_lineEdit_searchEditClients_cPhoneOut")
        self.ui_layout_searchEditClients.addWidget(self.ux_lineEdit_searchEditClients_cPhoneOut, 11, 5, 1, 1)
        self.ux_lineEdit_searchEditClients_cEmailOut = QtWidgets.QLineEdit(self.widget_searchEditClientsLayout)
        self.ux_lineEdit_searchEditClients_cEmailOut.setObjectName("ux_lineEdit_searchEditClients_cEmailOut")
        self.ui_layout_searchEditClients.addWidget(self.ux_lineEdit_searchEditClients_cEmailOut, 12, 5, 1, 1)
        self.ux_pButton_searchEditClients_finalizeInfo = QtWidgets.QPushButton(self.widget_searchEditClientsLayout)
        self.ux_pButton_searchEditClients_finalizeInfo.setObjectName("ux_pButton_searchEditClients_finalizeInfo")
        self.ui_layout_searchEditClients.addWidget(self.ux_pButton_searchEditClients_finalizeInfo, 14, 5, 1, 1)
        #self.ui_layout_dynamicMainView.addLayout(self.ui_layout_searchEditClients, 1, 0, 1, 1)

        # attach/set saerchEditClients layout to welcomePage widget
        self.widget_searchEditClientsLayout.setLayout(self.ui_layout_searchEditClients)
        self.stackedLayoutWidget.addWidget(self.widget_searchEditClientsLayout)

    ####################################################################################################################
    #
    #   ui_newProduct - window layout shown after "Add New Product" button click
    #
    ####################################################################################################################
    def ui_newProduct(self, stackedLayoutWidget):
        self.widget_newProductLayout = QtWidgets.QWidget(stackedLayoutWidget)
        self.widget_newProductLayout.setGeometry(QtCore.QRect(310, 20, 871, 681))
        self.widget_newProductLayout.setObjectName("widget_newProductLayout")
        self.ui_layout_newProduct = QtWidgets.QGridLayout()
        self.ui_layout_newProduct.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.ui_layout_newProduct.setSpacing(6)
        self.ui_layout_newProduct.setObjectName("ui_layout_newProduct")
        self.ux_lineEdit_newProduct_name = QtWidgets.QLineEdit(self.widget_newProductLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_lineEdit_newProduct_name.sizePolicy().hasHeightForWidth())
        self.ux_lineEdit_newProduct_name.setSizePolicy(sizePolicy)
        self.ux_lineEdit_newProduct_name.setMinimumSize(QtCore.QSize(200, 0))
        self.ux_lineEdit_newProduct_name.setObjectName("ux_lineEdit_newProduct_name")
        self.ui_layout_newProduct.addWidget(self.ux_lineEdit_newProduct_name, 2, 1, 1, 2)
        self.ux_label_newProduct_price = QtWidgets.QLabel(self.widget_newProductLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_label_newProduct_price.sizePolicy().hasHeightForWidth())
        self.ux_label_newProduct_price.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ux_label_newProduct_price.setFont(font)
        self.ux_label_newProduct_price.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.ux_label_newProduct_price.setObjectName("ux_label_newProduct_price")
        self.ui_layout_newProduct.addWidget(self.ux_label_newProduct_price, 6, 0, 1, 1)
        self.ux_lineEdit_newProduct_price = QtWidgets.QLineEdit(self.widget_newProductLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_lineEdit_newProduct_price.sizePolicy().hasHeightForWidth())
        self.ux_lineEdit_newProduct_price.setSizePolicy(sizePolicy)
        self.ux_lineEdit_newProduct_price.setMinimumSize(QtCore.QSize(200, 0))
        self.ux_lineEdit_newProduct_price.setObjectName("ux_lineEdit_newProduct_price")
        self.ui_layout_newProduct.addWidget(self.ux_lineEdit_newProduct_price, 6, 1, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.ui_layout_newProduct.addItem(spacerItem, 1, 1, 1, 2)
        self.ux_label_newProduct_name = QtWidgets.QLabel(self.widget_newProductLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_label_newProduct_name.sizePolicy().hasHeightForWidth())
        self.ux_label_newProduct_name.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ux_label_newProduct_name.setFont(font)
        self.ux_label_newProduct_name.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.ux_label_newProduct_name.setObjectName("ux_label_newProduct_name")
        self.ui_layout_newProduct.addWidget(self.ux_label_newProduct_name, 2, 0, 1, 1)
        self.ux_label_newProduct_description = QtWidgets.QLabel(self.widget_newProductLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_label_newProduct_description.sizePolicy().hasHeightForWidth())
        self.ux_label_newProduct_description.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ux_label_newProduct_description.setFont(font)
        self.ux_label_newProduct_description.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.ux_label_newProduct_description.setObjectName("ux_label_newProduct_description")
        self.ui_layout_newProduct.addWidget(self.ux_label_newProduct_description, 5, 0, 1, 1)
        self.ux_pButton_newProduct_addProd = QtWidgets.QPushButton(self.widget_newProductLayout)
        self.ux_pButton_newProduct_addProd.setMinimumSize(QtCore.QSize(0, 50))
        self.ux_pButton_newProduct_addProd.setObjectName("ux_pButton_newProduct_addProd")
        self.ui_layout_newProduct.addWidget(self.ux_pButton_newProduct_addProd, 11, 3, 1, 1)
        self.ui_label_newProduct_header = QtWidgets.QLabel(self.widget_newProductLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_label_newProduct_header.sizePolicy().hasHeightForWidth())
        self.ui_label_newProduct_header.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.ui_label_newProduct_header.setFont(font)
        self.ui_label_newProduct_header.setAlignment(QtCore.Qt.AlignCenter)
        self.ui_label_newProduct_header.setObjectName("ui_label_newProduct_header")
        self.ui_layout_newProduct.addWidget(self.ui_label_newProduct_header, 0, 0, 1, 4)
        self.ux_textEdit_newProduct_description = QtWidgets.QTextEdit(self.widget_newProductLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_textEdit_newProduct_description.sizePolicy().hasHeightForWidth())
        self.ux_textEdit_newProduct_description.setSizePolicy(sizePolicy)
        self.ux_textEdit_newProduct_description.setObjectName("ux_textEdit_newProduct_description")
        self.ui_layout_newProduct.addWidget(self.ux_textEdit_newProduct_description, 5, 1, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ui_layout_newProduct.addItem(spacerItem1, 10, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.ui_layout_newProduct.addItem(spacerItem2, 11, 2, 1, 1)

        # attach/set saerchEditClients layout to welcomePage widget
        self.widget_newProductLayout.setLayout(self.ui_layout_newProduct)
        self.stackedLayoutWidget.addWidget(self.widget_newProductLayout)



    ####################################################################################################################
    #
    #   ui_newProduct - window layout shown after "Add New Product" button click
    #
    ####################################################################################################################
    def ui_newInvoice(self, stackedLayoutWidget):
        self.widget_newInvoiceLayout = QtWidgets.QWidget(stackedLayoutWidget)
        self.widget_newInvoiceLayout.setContentsMargins(0, 0, 0, 0)
        self.widget_newInvoiceLayout.setObjectName("widget_newInvoiceLayout")
        self.ui_layout_newInvoice = QtWidgets.QGridLayout()
        self.ui_layout_newInvoice.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.ui_layout_newInvoice.setSpacing(6)
        self.ui_layout_newInvoice.setObjectName("ui_layout_newInvoice")
        self.ui_label_newInvoice_orderNumber = QtWidgets.QLabel(self.widget_newInvoiceLayout)
        self.ui_label_newInvoice_orderNumber.setObjectName("ui_label_newInvoice_orderNumber")
        self.ui_layout_newInvoice.addWidget(self.ui_label_newInvoice_orderNumber, 17, 3, 1, 1)
        self.ux_lineEdit_newInvoice_orderSubTotal = QtWidgets.QLineEdit(self.widget_newInvoiceLayout)
        self.ux_lineEdit_newInvoice_orderSubTotal.setObjectName("ux_lineEdit_newInvoice_orderSubTotal")
        self.ui_layout_newInvoice.addWidget(self.ux_lineEdit_newInvoice_orderSubTotal, 19, 5, 1, 1)
        self.ui_label_newInvoice_orderSubTotal = QtWidgets.QLabel(self.widget_newInvoiceLayout)
        self.ui_label_newInvoice_orderSubTotal.setObjectName("ui_label_newInvoice_orderSubTotal")
        self.ui_layout_newInvoice.addWidget(self.ui_label_newInvoice_orderSubTotal, 19, 3, 1, 1)
        self.ui_label_newInvoice_doubleClickTo_2 = QtWidgets.QLabel(self.widget_newInvoiceLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_label_newInvoice_doubleClickTo_2.sizePolicy().hasHeightForWidth())
        self.ui_label_newInvoice_doubleClickTo_2.setSizePolicy(sizePolicy)
        self.ui_label_newInvoice_doubleClickTo_2.setObjectName("ui_label_newInvoice_doubleClickTo_2")
        self.ui_layout_newInvoice.addWidget(self.ui_label_newInvoice_doubleClickTo_2, 16, 1, 1, 1)
        self.ui_label_newInvoice_doubleClickTo = QtWidgets.QLabel(self.widget_newInvoiceLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_label_newInvoice_doubleClickTo.sizePolicy().hasHeightForWidth())
        self.ui_label_newInvoice_doubleClickTo.setSizePolicy(sizePolicy)
        self.ui_label_newInvoice_doubleClickTo.setObjectName("ui_label_newInvoice_doubleClickTo")
        self.ui_layout_newInvoice.addWidget(self.ui_label_newInvoice_doubleClickTo, 5, 1, 1, 1)
        self.ux_lineEdit_newInvoice_clientNameSearch = QtWidgets.QLineEdit(self.widget_newInvoiceLayout)
        self.ux_lineEdit_newInvoice_clientNameSearch.setObjectName("ux_lineEdit_newInvoice_clientNameSearch")
        self.ui_layout_newInvoice.addWidget(self.ux_lineEdit_newInvoice_clientNameSearch, 3, 1, 1, 1)
        self.ui_label_newInvoice_clientEmail = QtWidgets.QLabel(self.widget_newInvoiceLayout)
        self.ui_label_newInvoice_clientEmail.setObjectName("ui_label_newInvoice_clientEmail")
        self.ui_layout_newInvoice.addWidget(self.ui_label_newInvoice_clientEmail, 12, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ui_layout_newInvoice.addItem(spacerItem, 0, 0, 1, 1)
        self.ui_label_newInvoice_addressLine1 = QtWidgets.QLabel(self.widget_newInvoiceLayout)
        self.ui_label_newInvoice_addressLine1.setObjectName("ui_label_newInvoice_addressLine1")
        self.ui_layout_newInvoice.addWidget(self.ui_label_newInvoice_addressLine1, 9, 3, 1, 1)
        self.ui_label_newInvoice_addressLine2 = QtWidgets.QLabel(self.widget_newInvoiceLayout)
        self.ui_label_newInvoice_addressLine2.setObjectName("ui_label_newInvoice_addressLine2")
        self.ui_layout_newInvoice.addWidget(self.ui_label_newInvoice_addressLine2, 10, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.ui_layout_newInvoice.addItem(spacerItem1, 1, 2, 1, 1)
        self.ui_label_newInvoice_typeBelow = QtWidgets.QLabel(self.widget_newInvoiceLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_label_newInvoice_typeBelow.sizePolicy().hasHeightForWidth())
        self.ui_label_newInvoice_typeBelow.setSizePolicy(sizePolicy)
        self.ui_label_newInvoice_typeBelow.setObjectName("ui_label_newInvoice_typeBelow")
        self.ui_layout_newInvoice.addWidget(self.ui_label_newInvoice_typeBelow, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ui_layout_newInvoice.addItem(spacerItem2, 8, 6, 1, 1)
        self.ui_label_newInvoice_header = QtWidgets.QLabel(self.widget_newInvoiceLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_label_newInvoice_header.sizePolicy().hasHeightForWidth())
        self.ui_label_newInvoice_header.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.ui_label_newInvoice_header.setFont(font)
        self.ui_label_newInvoice_header.setAlignment(QtCore.Qt.AlignCenter)
        self.ui_label_newInvoice_header.setObjectName("ui_label_newInvoice_header")
        self.ui_layout_newInvoice.addWidget(self.ui_label_newInvoice_header, 0, 1, 1, 5)
        self.ux_pButton_newInvoice_showAllOrders = QtWidgets.QPushButton(self.widget_newInvoiceLayout)
        self.ux_pButton_newInvoice_showAllOrders.setObjectName("ux_pButton_newInvoice_showAllOrders")
        self.ui_layout_newInvoice.addWidget(self.ux_pButton_newInvoice_showAllOrders, 23, 1, 1, 1)
        self.ux_lineEdit_newInvoice_orderNumber = QtWidgets.QLineEdit(self.widget_newInvoiceLayout)
        self.ux_lineEdit_newInvoice_orderNumber.setObjectName("ux_lineEdit_newInvoice_orderNumber")
        self.ui_layout_newInvoice.addWidget(self.ux_lineEdit_newInvoice_orderNumber, 17, 5, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ui_layout_newInvoice.addItem(spacerItem3, 3, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ui_layout_newInvoice.addItem(spacerItem4, 8, 4, 1, 1)
        self.ux_lineEdit_newInvoice_cNameOut = QtWidgets.QLineEdit(self.widget_newInvoiceLayout)
        self.ux_lineEdit_newInvoice_cNameOut.setObjectName("ux_lineEdit_newInvoice_cNameOut")
        self.ui_layout_newInvoice.addWidget(self.ux_lineEdit_newInvoice_cNameOut, 8, 5, 1, 1)
        self.ui_label_newInvoice_clientPhone = QtWidgets.QLabel(self.widget_newInvoiceLayout)
        self.ui_label_newInvoice_clientPhone.setObjectName("ui_label_newInvoice_clientPhone")
        self.ui_layout_newInvoice.addWidget(self.ui_label_newInvoice_clientPhone, 11, 3, 1, 1)
        self.ux_lineEdit_newInvoice_address1Out = QtWidgets.QLineEdit(self.widget_newInvoiceLayout)
        self.ux_lineEdit_newInvoice_address1Out.setObjectName("ux_lineEdit_newInvoice_address1Out")
        self.ui_layout_newInvoice.addWidget(self.ux_lineEdit_newInvoice_address1Out, 9, 5, 1, 1)
        self.ux_lineEdit_newInvoice_address2Out = QtWidgets.QLineEdit(self.widget_newInvoiceLayout)
        self.ux_lineEdit_newInvoice_address2Out.setObjectName("ux_lineEdit_newInvoice_address2Out")
        self.ui_layout_newInvoice.addWidget(self.ux_lineEdit_newInvoice_address2Out, 10, 5, 1, 1)
        self.ux_lineEdit_newInvoice_cEmailOut = QtWidgets.QLineEdit(self.widget_newInvoiceLayout)
        self.ux_lineEdit_newInvoice_cEmailOut.setObjectName("ux_lineEdit_newInvoice_cEmailOut")
        self.ui_layout_newInvoice.addWidget(self.ux_lineEdit_newInvoice_cEmailOut, 12, 5, 1, 1)
        self.ux_lineEdit_newInvoice_cPhoneOut = QtWidgets.QLineEdit(self.widget_newInvoiceLayout)
        self.ux_lineEdit_newInvoice_cPhoneOut.setObjectName("ux_lineEdit_newInvoice_cPhoneOut")
        self.ui_layout_newInvoice.addWidget(self.ux_lineEdit_newInvoice_cPhoneOut, 11, 5, 1, 1)
        self.ui_label_newInvoice_taxApplied = QtWidgets.QLabel(self.widget_newInvoiceLayout)
        self.ui_label_newInvoice_taxApplied.setObjectName("ui_label_newInvoice_taxApplied")
        self.ui_layout_newInvoice.addWidget(self.ui_label_newInvoice_taxApplied, 20, 3, 1, 1)
        self.ui_label_newInvoice_orderTotal = QtWidgets.QLabel(self.widget_newInvoiceLayout)
        self.ui_label_newInvoice_orderTotal.setObjectName("ui_label_newInvoice_orderTotal")
        self.ui_layout_newInvoice.addWidget(self.ui_label_newInvoice_orderTotal, 21, 3, 1, 1)
        self.ux_lineEdit_newInvoice_taxApplied = QtWidgets.QLineEdit(self.widget_newInvoiceLayout)
        self.ux_lineEdit_newInvoice_taxApplied.setObjectName("ux_lineEdit_newInvoice_taxApplied")
        self.ui_layout_newInvoice.addWidget(self.ux_lineEdit_newInvoice_taxApplied, 20, 5, 1, 1)
        self.ui_ListView_newInvoice_orderSearchList = QtWidgets.QListView(self.widget_newInvoiceLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_ListView_newInvoice_orderSearchList.sizePolicy().hasHeightForWidth())
        self.ui_ListView_newInvoice_orderSearchList.setSizePolicy(sizePolicy)
        self.ui_ListView_newInvoice_orderSearchList.setObjectName("ui_ListView_newInvoice_orderSearchList")
        self.ui_layout_newInvoice.addWidget(self.ui_ListView_newInvoice_orderSearchList, 17, 1, 5, 1)
        self.ui_label_newInvoice_clientName = QtWidgets.QLabel(self.widget_newInvoiceLayout)
        self.ui_label_newInvoice_clientName.setObjectName("ui_label_newInvoice_clientName")
        self.ui_layout_newInvoice.addWidget(self.ui_label_newInvoice_clientName, 8, 3, 1, 1)
        self.ui_label_newInvoice_orderItems = QtWidgets.QLabel(self.widget_newInvoiceLayout)
        self.ui_label_newInvoice_orderItems.setObjectName("ui_label_newInvoice_orderItems")
        self.ui_layout_newInvoice.addWidget(self.ui_label_newInvoice_orderItems, 18, 3, 1, 1)
        self.ui_ListView_newInvoice_nameSearchList = QtWidgets.QListView(self.widget_newInvoiceLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_ListView_newInvoice_nameSearchList.sizePolicy().hasHeightForWidth())
        self.ui_ListView_newInvoice_nameSearchList.setSizePolicy(sizePolicy)
        self.ui_ListView_newInvoice_nameSearchList.setObjectName("ui_ListView_newInvoice_nameSearchList")

        # set model for listView containing client names
        self.ui_ListView_newInvoice_nameSearchList.setModel(self.model_listView_newInvoice_nameSearchList)

        self.ui_layout_newInvoice.addWidget(self.ui_ListView_newInvoice_nameSearchList, 8, 1, 5, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.ui_layout_newInvoice.addItem(spacerItem5, 25, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.ui_layout_newInvoice.addItem(spacerItem6, 13, 1, 3, 1)
        self.ux_pButton_newInvoice_ShowUnpaidOrders = QtWidgets.QPushButton(self.widget_newInvoiceLayout)
        self.ux_pButton_newInvoice_ShowUnpaidOrders.setObjectName("ux_pButton_newInvoice_ShowUnpaidOrders")
        self.ui_layout_newInvoice.addWidget(self.ux_pButton_newInvoice_ShowUnpaidOrders, 22, 1, 1, 1)
        self.ui_tableView_newInvoice_orderItems = QtWidgets.QTableView(self.widget_newInvoiceLayout)
        self.ui_tableView_newInvoice_orderItems.setObjectName("ui_tableView_newInvoice_orderItems")
        self.ui_layout_newInvoice.addWidget(self.ui_tableView_newInvoice_orderItems, 18, 5, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.ui_layout_newInvoice.addItem(spacerItem7, 24, 1, 1, 1)
        self.ux_lineEdit_newInvoice_orderTotal = QtWidgets.QLineEdit(self.widget_newInvoiceLayout)
        self.ux_lineEdit_newInvoice_orderTotal.setObjectName("ux_lineEdit_newInvoice_orderTotal")
        self.ui_layout_newInvoice.addWidget(self.ux_lineEdit_newInvoice_orderTotal, 21, 5, 1, 1)
        self.ux_pButton_newInvoice_createInvoice = QtWidgets.QPushButton(self.widget_newInvoiceLayout)
        self.ux_pButton_newInvoice_createInvoice.setObjectName("ux_pButton_newInvoice_createInvoice")
        self.ui_layout_newInvoice.addWidget(self.ux_pButton_newInvoice_createInvoice, 22, 5, 1, 1)
        self.ux_pButton_newInvoice_createAndSendInvoice = QtWidgets.QPushButton(self.widget_newInvoiceLayout)
        self.ux_pButton_newInvoice_createAndSendInvoice.setObjectName("ux_pButton_newInvoice_createAndSendInvoice")
        self.ui_layout_newInvoice.addWidget(self.ux_pButton_newInvoice_createAndSendInvoice, 23, 5, 1, 1)
        #self.widget_newInvoiceLayout.addLayout(self.ui_layout_newInvoice, 1, 0, 1, 1)

        # attach/set saerchEditClients layout to newProduct widget
        self.widget_newInvoiceLayout.setLayout(self.ui_layout_newInvoice)
        self.stackedLayoutWidget.addWidget(self.widget_newInvoiceLayout)

    ####################################################################################################################
    #
    #   ui_newInvoiceCandS - window layout shown after "Add New Product" button click
    #
    ####################################################################################################################
    def ui_newInvoiceCandS(self, stackedLayoutWidget, model):
        self.widget_newInvoiceCandSLayout = QtWidgets.QWidget(stackedLayoutWidget)
        self.widget_newInvoiceCandSLayout.setContentsMargins(0, 0, 0, 0)
        self.widget_newInvoiceCandSLayout.setObjectName("widget_newInvoiceCandSLayout")
        self.ui_layout_newInvoiceCandS = QtWidgets.QGridLayout()
        self.ui_layout_newInvoiceCandS.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.ui_layout_newInvoiceCandS.setSpacing(6)
        self.ui_layout_newInvoiceCandS.setObjectName("ui_layout_newInvoiceCandS")
        self.ui_label_newInvoiceCandS_orderSubTotal = QtWidgets.QLabel(self.widget_newInvoiceCandSLayout)
        self.ui_label_newInvoiceCandS_orderSubTotal.setObjectName("ui_label_newInvoiceCandS_orderSubTotal")
        self.ui_layout_newInvoiceCandS.addWidget(self.ui_label_newInvoiceCandS_orderSubTotal, 14, 3, 1, 1)
        self.ux_lineEdit_newInvoiceCandS_orderSubTotal = QtWidgets.QLineEdit(self.widget_newInvoiceCandSLayout)
        self.ux_lineEdit_newInvoiceCandS_orderSubTotal.setObjectName("ux_lineEdit_newInvoiceCandS_orderSubTotal")
        self.ui_layout_newInvoiceCandS.addWidget(self.ux_lineEdit_newInvoiceCandS_orderSubTotal, 14, 5, 1, 1)
        self.ui_label_newInvoiceCandS_addressLine1 = QtWidgets.QLabel(self.widget_newInvoiceCandSLayout)
        self.ui_label_newInvoiceCandS_addressLine1.setObjectName("ui_label_newInvoiceCandS_addressLine1")
        self.ui_layout_newInvoiceCandS.addWidget(self.ui_label_newInvoiceCandS_addressLine1, 7, 3, 1, 1)
        self.ui_label_newInvoiceCandS_clientEmail = QtWidgets.QLabel(self.widget_newInvoiceCandSLayout)
        self.ui_label_newInvoiceCandS_clientEmail.setObjectName("ui_label_newInvoiceCandS_clientEmail")
        self.ui_layout_newInvoiceCandS.addWidget(self.ui_label_newInvoiceCandS_clientEmail, 10, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.ui_layout_newInvoiceCandS.addItem(spacerItem, 1, 2, 1, 1)
        self.ui_label_newInvoiceCandS_addressLine2 = QtWidgets.QLabel(self.widget_newInvoiceCandSLayout)
        self.ui_label_newInvoiceCandS_addressLine2.setObjectName("ui_label_newInvoiceCandS_addressLine2")
        self.ui_layout_newInvoiceCandS.addWidget(self.ui_label_newInvoiceCandS_addressLine2, 8, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ui_layout_newInvoiceCandS.addItem(spacerItem1, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ui_layout_newInvoiceCandS.addItem(spacerItem2, 6, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ui_layout_newInvoiceCandS.addItem(spacerItem3, 2, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ui_layout_newInvoiceCandS.addItem(spacerItem4, 6, 6, 1, 1)
        self.ui_label_newInvoiceCandS_header = QtWidgets.QLabel(self.widget_newInvoiceCandSLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_label_newInvoiceCandS_header.sizePolicy().hasHeightForWidth())
        self.ui_label_newInvoiceCandS_header.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.ui_label_newInvoiceCandS_header.setFont(font)
        self.ui_label_newInvoiceCandS_header.setAlignment(QtCore.Qt.AlignCenter)
        self.ui_label_newInvoiceCandS_header.setObjectName("ui_label_newInvoiceCandS_header")
        self.ui_layout_newInvoiceCandS.addWidget(self.ui_label_newInvoiceCandS_header, 0, 1, 1, 5)
        self.ux_pButton_newInvoiceCandS_showAllOrders = QtWidgets.QPushButton(self.widget_newInvoiceCandSLayout)
        self.ux_pButton_newInvoiceCandS_showAllOrders.setObjectName("ux_pButton_newInvoiceCandS_showAllOrders")
        self.ui_layout_newInvoiceCandS.addWidget(self.ux_pButton_newInvoiceCandS_showAllOrders, 18, 1, 1, 1)
        self.ux_lineEdit_newInvoiceCandS_address2Out = QtWidgets.QLineEdit(self.widget_newInvoiceCandSLayout)
        self.ux_lineEdit_newInvoiceCandS_address2Out.setObjectName("ux_lineEdit_newInvoiceCandS_address2Out")
        self.ui_layout_newInvoiceCandS.addWidget(self.ux_lineEdit_newInvoiceCandS_address2Out, 8, 5, 1, 1)
        self.ux_lineEdit_newInvoiceCandS_address1Out = QtWidgets.QLineEdit(self.widget_newInvoiceCandSLayout)
        self.ux_lineEdit_newInvoiceCandS_address1Out.setObjectName("ux_lineEdit_newInvoiceCandS_address1Out")
        self.ui_layout_newInvoiceCandS.addWidget(self.ux_lineEdit_newInvoiceCandS_address1Out, 7, 5, 1, 1)
        self.ux_lineEdit_newInvoiceCandS_cEmailOut = QtWidgets.QLineEdit(self.widget_newInvoiceCandSLayout)
        self.ux_lineEdit_newInvoiceCandS_cEmailOut.setObjectName("ux_lineEdit_newInvoiceCandS_cEmailOut")
        self.ui_layout_newInvoiceCandS.addWidget(self.ux_lineEdit_newInvoiceCandS_cEmailOut, 10, 5, 1, 1)
        self.ui_label_newInvoiceCandS_clientPhone = QtWidgets.QLabel(self.widget_newInvoiceCandSLayout)
        self.ui_label_newInvoiceCandS_clientPhone.setObjectName("ui_label_newInvoiceCandS_clientPhone")
        self.ui_layout_newInvoiceCandS.addWidget(self.ui_label_newInvoiceCandS_clientPhone, 9, 3, 1, 1)
        self.ux_lineEdit_newInvoiceCandS_cNameOut = QtWidgets.QLineEdit(self.widget_newInvoiceCandSLayout)
        self.ux_lineEdit_newInvoiceCandS_cNameOut.setObjectName("ux_lineEdit_newInvoiceCandS_cNameOut")
        self.ui_layout_newInvoiceCandS.addWidget(self.ux_lineEdit_newInvoiceCandS_cNameOut, 6, 5, 1, 1)
        self.ui_label_newInvoiceCandS_orderTotal = QtWidgets.QLabel(self.widget_newInvoiceCandSLayout)
        self.ui_label_newInvoiceCandS_orderTotal.setObjectName("ui_label_newInvoiceCandS_orderTotal")
        self.ui_layout_newInvoiceCandS.addWidget(self.ui_label_newInvoiceCandS_orderTotal, 16, 3, 1, 1)
        self.ux_lineEdit_newInvoiceCandS_taxApplied = QtWidgets.QLineEdit(self.widget_newInvoiceCandSLayout)
        self.ux_lineEdit_newInvoiceCandS_taxApplied.setObjectName("ux_lineEdit_newInvoiceCandS_taxApplied")
        self.ui_layout_newInvoiceCandS.addWidget(self.ux_lineEdit_newInvoiceCandS_taxApplied, 15, 5, 1, 1)
        self.ux_lineEdit_newInvoiceCandS_cPhoneOut = QtWidgets.QLineEdit(self.widget_newInvoiceCandSLayout)
        self.ux_lineEdit_newInvoiceCandS_cPhoneOut.setObjectName("ux_lineEdit_newInvoiceCandS_cPhoneOut")
        self.ui_layout_newInvoiceCandS.addWidget(self.ux_lineEdit_newInvoiceCandS_cPhoneOut, 9, 5, 1, 1)
        self.ui_label_newInvoiceCandS_taxApplied = QtWidgets.QLabel(self.widget_newInvoiceCandSLayout)
        self.ui_label_newInvoiceCandS_taxApplied.setObjectName("ui_label_newInvoiceCandS_taxApplied")
        self.ui_layout_newInvoiceCandS.addWidget(self.ui_label_newInvoiceCandS_taxApplied, 15, 3, 1, 1)
        self.ui_label_newInvoiceCandS_clientName = QtWidgets.QLabel(self.widget_newInvoiceCandSLayout)
        self.ui_label_newInvoiceCandS_clientName.setObjectName("ui_label_newInvoiceCandS_clientName")
        self.ui_layout_newInvoiceCandS.addWidget(self.ui_label_newInvoiceCandS_clientName, 6, 3, 1, 1)
        self.ui_label_newInvoiceCandS_orderItems = QtWidgets.QLabel(self.widget_newInvoiceCandSLayout)
        self.ui_label_newInvoiceCandS_orderItems.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.ui_label_newInvoiceCandS_orderItems.setObjectName("ui_label_newInvoiceCandS_orderItems")
        self.ui_layout_newInvoiceCandS.addWidget(self.ui_label_newInvoiceCandS_orderItems, 13, 3, 1, 1)
        self.ux_pButton_newInvoiceCandS_ShowUnsentOrders = QtWidgets.QPushButton(self.widget_newInvoiceCandSLayout)
        self.ux_pButton_newInvoiceCandS_ShowUnsentOrders.setObjectName("ux_pButton_newInvoiceCandS_ShowUnsentOrders")
        self.ui_layout_newInvoiceCandS.addWidget(self.ux_pButton_newInvoiceCandS_ShowUnsentOrders, 17, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.ui_layout_newInvoiceCandS.addItem(spacerItem5, 19, 1, 1, 1)
        self.ux_lineEdit_newInvoiceCandS_orderTotal = QtWidgets.QLineEdit(self.widget_newInvoiceCandSLayout)
        self.ux_lineEdit_newInvoiceCandS_orderTotal.setObjectName("ux_lineEdit_newInvoiceCandS_orderTotal")
        self.ui_layout_newInvoiceCandS.addWidget(self.ux_lineEdit_newInvoiceCandS_orderTotal, 16, 5, 1, 1)
        self.ui_listView_newInvoiceCandS_orderItems = QtWidgets.QListView(self.widget_newInvoiceCandSLayout)
        self.ui_listView_newInvoiceCandS_orderItems.setObjectName("ui_listView_newInvoiceCandS_orderItems")

        # set model for tableView
        self.ui_listView_newInvoiceCandS_orderItems.setModel(model.model_listView_newInvoiceCandS_orderList)

        self.ui_layout_newInvoiceCandS.addWidget(self.ui_listView_newInvoiceCandS_orderItems, 13, 5, 1, 1)
        self.ui_label_newInvoiceCandS_doubleClickTo = QtWidgets.QLabel(self.widget_newInvoiceCandSLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_label_newInvoiceCandS_doubleClickTo.sizePolicy().hasHeightForWidth())
        self.ui_label_newInvoiceCandS_doubleClickTo.setSizePolicy(sizePolicy)
        self.ui_label_newInvoiceCandS_doubleClickTo.setObjectName("ui_label_newInvoiceCandS_doubleClickTo")
        self.ui_layout_newInvoiceCandS.addWidget(self.ui_label_newInvoiceCandS_doubleClickTo, 6, 1, 1, 1)
        self.ui_label_newInvoiceCandS_clickBelowToSend = QtWidgets.QLabel(self.widget_newInvoiceCandSLayout)
        self.ui_label_newInvoiceCandS_clickBelowToSend.setObjectName("ui_label_newInvoiceCandS_clickBelowToSend")
        self.ui_layout_newInvoiceCandS.addWidget(self.ui_label_newInvoiceCandS_clickBelowToSend, 17, 5, 1, 1)
        self.ui_label_newInvoiceCandS_orderNumber = QtWidgets.QLabel(self.widget_newInvoiceCandSLayout)
        self.ui_label_newInvoiceCandS_orderNumber.setObjectName("ui_label_newInvoiceCandS_orderNumber")
        self.ui_layout_newInvoiceCandS.addWidget(self.ui_label_newInvoiceCandS_orderNumber, 11, 3, 1, 1)
        self.ui_ListView_newInvoiceCandS_orderSearchList = QtWidgets.QListView(self.widget_newInvoiceCandSLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_ListView_newInvoiceCandS_orderSearchList.sizePolicy().hasHeightForWidth())
        self.ui_ListView_newInvoiceCandS_orderSearchList.setSizePolicy(sizePolicy)
        self.ui_ListView_newInvoiceCandS_orderSearchList.setObjectName("ui_ListView_newInvoiceCandS_orderSearchList")
        self.ui_layout_newInvoiceCandS.addWidget(self.ui_ListView_newInvoiceCandS_orderSearchList, 7, 1, 10, 1)
        self.ux_lineEdit_newInvoiceCandS_orderNumber = QtWidgets.QLineEdit(self.widget_newInvoiceCandSLayout)
        self.ux_lineEdit_newInvoiceCandS_orderNumber.setObjectName("ux_lineEdit_newInvoiceCandS_orderNumber")
        self.ui_layout_newInvoiceCandS.addWidget(self.ux_lineEdit_newInvoiceCandS_orderNumber, 11, 5, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.ui_layout_newInvoiceCandS.addItem(spacerItem6, 20, 1, 1, 1)
        self.ux_pButton_newInvoiceCandS_createAndSendInvoice = QtWidgets.QPushButton(self.widget_newInvoiceCandSLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.ux_pButton_newInvoiceCandS_createAndSendInvoice.sizePolicy().hasHeightForWidth())
        self.ux_pButton_newInvoiceCandS_createAndSendInvoice.setSizePolicy(sizePolicy)
        self.ux_pButton_newInvoiceCandS_createAndSendInvoice.setObjectName(
            "ux_pButton_newInvoiceCandS_createAndSendInvoice")
        self.ui_layout_newInvoiceCandS.addWidget(self.ux_pButton_newInvoiceCandS_createAndSendInvoice, 18, 5, 2, 1)

        # attach/set newInvoiceCandS layout to newInvoiceCandS widget
        self.widget_newInvoiceCandSLayout.setLayout(self.ui_layout_newInvoiceCandS)
        self.stackedLayoutWidget.addWidget(self.widget_newInvoiceCandSLayout)