# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout_newInvoiceCandS.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_mainView(object):
    def setupUi(self, MainWindow_mainView):
        MainWindow_mainView.setObjectName("MainWindow_mainView")
        MainWindow_mainView.resize(1196, 711)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow_mainView.sizePolicy().hasHeightForWidth())
        MainWindow_mainView.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow_mainView)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(310, 20, 871, 683))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.widget_newInvoiceCandSLayout = QtWidgets.QtWidgets.QWidget(stackedLayoutWidget)
        self.widget_newInvoiceCandSLayout.setContentsMargins(0, 0, 0, 0)
        self.widget_newInvoiceCandSLayout.setObjectName("widget_newInvoiceCandSLayout")
        self.ui_layout_newInvoiceCandS = QtWidgets.QGridLayout()
        self.ui_layout_newInvoiceCandS.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.ui_layout_newInvoiceCandS.setSpacing(6)
        self.ui_layout_newInvoiceCandS.setObjectName("ui_layout_newInvoiceCandS")
        self.ui_label_newInvoiceCandS_orderSubTotal = QtWidgets.QLabel(self.gridLayoutWidget)
        self.ui_label_newInvoiceCandS_orderSubTotal.setObjectName("ui_label_newInvoiceCandS_orderSubTotal")
        self.ui_layout_newInvoiceCandS.addWidget(self.ui_label_newInvoiceCandS_orderSubTotal, 14, 3, 1, 1)
        self.ux_lineEdit_newInvoiceCandS_orderSubTotal = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.ux_lineEdit_newInvoiceCandS_orderSubTotal.setObjectName("ux_lineEdit_newInvoiceCandS_orderSubTotal")
        self.ui_layout_newInvoiceCandS.addWidget(self.ux_lineEdit_newInvoiceCandS_orderSubTotal, 14, 5, 1, 1)
        self.ui_label_newInvoiceCandS_addressLine1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.ui_label_newInvoiceCandS_addressLine1.setObjectName("ui_label_newInvoiceCandS_addressLine1")
        self.ui_layout_newInvoiceCandS.addWidget(self.ui_label_newInvoiceCandS_addressLine1, 7, 3, 1, 1)
        self.ui_label_newInvoiceCandS_clientEmail = QtWidgets.QLabel(self.gridLayoutWidget)
        self.ui_label_newInvoiceCandS_clientEmail.setObjectName("ui_label_newInvoiceCandS_clientEmail")
        self.ui_layout_newInvoiceCandS.addWidget(self.ui_label_newInvoiceCandS_clientEmail, 10, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.ui_layout_newInvoiceCandS.addItem(spacerItem, 1, 2, 1, 1)
        self.ui_label_newInvoiceCandS_addressLine2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.ui_label_newInvoiceCandS_addressLine2.setObjectName("ui_label_newInvoiceCandS_addressLine2")
        self.ui_layout_newInvoiceCandS.addWidget(self.ui_label_newInvoiceCandS_addressLine2, 8, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ui_layout_newInvoiceCandS.addItem(spacerItem1, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ui_layout_newInvoiceCandS.addItem(spacerItem2, 6, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ui_layout_newInvoiceCandS.addItem(spacerItem3, 2, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ui_layout_newInvoiceCandS.addItem(spacerItem4, 6, 6, 1, 1)
        self.ui_label_newInvoiceCandS_header = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_label_newInvoiceCandS_header.sizePolicy().hasHeightForWidth())
        self.ui_label_newInvoiceCandS_header.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.ui_label_newInvoiceCandS_header.setFont(font)
        self.ui_label_newInvoiceCandS_header.setAlignment(QtCore.Qt.AlignCenter)
        self.ui_label_newInvoiceCandS_header.setObjectName("ui_label_newInvoiceCandS_header")
        self.ui_layout_newInvoiceCandS.addWidget(self.ui_label_newInvoiceCandS_header, 0, 1, 1, 5)
        self.ux_pButton_newInvoiceCandS_showAllOrders = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ux_pButton_newInvoiceCandS_showAllOrders.setObjectName("ux_pButton_newInvoiceCandS_showAllOrders")
        self.ui_layout_newInvoiceCandS.addWidget(self.ux_pButton_newInvoiceCandS_showAllOrders, 18, 1, 1, 1)
        self.ux_lineEdit_newInvoiceCandS_address2Out = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.ux_lineEdit_newInvoiceCandS_address2Out.setObjectName("ux_lineEdit_newInvoiceCandS_address2Out")
        self.ui_layout_newInvoiceCandS.addWidget(self.ux_lineEdit_newInvoiceCandS_address2Out, 8, 5, 1, 1)
        self.ux_lineEdit_newInvoiceCandS_address1Out = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.ux_lineEdit_newInvoiceCandS_address1Out.setObjectName("ux_lineEdit_newInvoiceCandS_address1Out")
        self.ui_layout_newInvoiceCandS.addWidget(self.ux_lineEdit_newInvoiceCandS_address1Out, 7, 5, 1, 1)
        self.ux_lineEdit_newInvoiceCandS_cEmailOut = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.ux_lineEdit_newInvoiceCandS_cEmailOut.setObjectName("ux_lineEdit_newInvoiceCandS_cEmailOut")
        self.ui_layout_newInvoiceCandS.addWidget(self.ux_lineEdit_newInvoiceCandS_cEmailOut, 10, 5, 1, 1)
        self.ui_label_newInvoiceCandS_clientPhone = QtWidgets.QLabel(self.gridLayoutWidget)
        self.ui_label_newInvoiceCandS_clientPhone.setObjectName("ui_label_newInvoiceCandS_clientPhone")
        self.ui_layout_newInvoiceCandS.addWidget(self.ui_label_newInvoiceCandS_clientPhone, 9, 3, 1, 1)
        self.ux_lineEdit_newInvoiceCandS_cNameOut = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.ux_lineEdit_newInvoiceCandS_cNameOut.setObjectName("ux_lineEdit_newInvoiceCandS_cNameOut")
        self.ui_layout_newInvoiceCandS.addWidget(self.ux_lineEdit_newInvoiceCandS_cNameOut, 6, 5, 1, 1)
        self.ui_label_newInvoiceCandS_orderTotal = QtWidgets.QLabel(self.gridLayoutWidget)
        self.ui_label_newInvoiceCandS_orderTotal.setObjectName("ui_label_newInvoiceCandS_orderTotal")
        self.ui_layout_newInvoiceCandS.addWidget(self.ui_label_newInvoiceCandS_orderTotal, 16, 3, 1, 1)
        self.ux_lineEdit_newInvoiceCandS_taxApplied = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.ux_lineEdit_newInvoiceCandS_taxApplied.setObjectName("ux_lineEdit_newInvoiceCandS_taxApplied")
        self.ui_layout_newInvoiceCandS.addWidget(self.ux_lineEdit_newInvoiceCandS_taxApplied, 15, 5, 1, 1)
        self.ux_lineEdit_newInvoiceCandS_cPhoneOut = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.ux_lineEdit_newInvoiceCandS_cPhoneOut.setObjectName("ux_lineEdit_newInvoiceCandS_cPhoneOut")
        self.ui_layout_newInvoiceCandS.addWidget(self.ux_lineEdit_newInvoiceCandS_cPhoneOut, 9, 5, 1, 1)
        self.ui_label_newInvoiceCandS_taxApplied = QtWidgets.QLabel(self.gridLayoutWidget)
        self.ui_label_newInvoiceCandS_taxApplied.setObjectName("ui_label_newInvoiceCandS_taxApplied")
        self.ui_layout_newInvoiceCandS.addWidget(self.ui_label_newInvoiceCandS_taxApplied, 15, 3, 1, 1)
        self.ui_label_newInvoiceCandS_clientName = QtWidgets.QLabel(self.gridLayoutWidget)
        self.ui_label_newInvoiceCandS_clientName.setObjectName("ui_label_newInvoiceCandS_clientName")
        self.ui_layout_newInvoiceCandS.addWidget(self.ui_label_newInvoiceCandS_clientName, 6, 3, 1, 1)
        self.ui_label_newInvoiceCandS_orderItems = QtWidgets.QLabel(self.gridLayoutWidget)
        self.ui_label_newInvoiceCandS_orderItems.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ui_label_newInvoiceCandS_orderItems.setObjectName("ui_label_newInvoiceCandS_orderItems")
        self.ui_layout_newInvoiceCandS.addWidget(self.ui_label_newInvoiceCandS_orderItems, 13, 3, 1, 1)
        self.ux_pButton_newInvoiceCandS_ShowUnsentOrders = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ux_pButton_newInvoiceCandS_ShowUnsentOrders.setObjectName("ux_pButton_newInvoiceCandS_ShowUnsentOrders")
        self.ui_layout_newInvoiceCandS.addWidget(self.ux_pButton_newInvoiceCandS_ShowUnsentOrders, 17, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.ui_layout_newInvoiceCandS.addItem(spacerItem5, 19, 1, 1, 1)
        self.ux_lineEdit_newInvoiceCandS_orderTotal = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.ux_lineEdit_newInvoiceCandS_orderTotal.setObjectName("ux_lineEdit_newInvoiceCandS_orderTotal")
        self.ui_layout_newInvoiceCandS.addWidget(self.ux_lineEdit_newInvoiceCandS_orderTotal, 16, 5, 1, 1)
        self.ui_tableView_newInvoiceCandS_orderItems = QtWidgets.QTableView(self.gridLayoutWidget)
        self.ui_tableView_newInvoiceCandS_orderItems.setObjectName("ui_tableView_newInvoiceCandS_orderItems")
        self.ui_layout_newInvoiceCandS.addWidget(self.ui_tableView_newInvoiceCandS_orderItems, 13, 5, 1, 1)
        self.ui_label_newInvoiceCandS_doubleClickTo = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_label_newInvoiceCandS_doubleClickTo.sizePolicy().hasHeightForWidth())
        self.ui_label_newInvoiceCandS_doubleClickTo.setSizePolicy(sizePolicy)
        self.ui_label_newInvoiceCandS_doubleClickTo.setObjectName("ui_label_newInvoiceCandS_doubleClickTo")
        self.ui_layout_newInvoiceCandS.addWidget(self.ui_label_newInvoiceCandS_doubleClickTo, 6, 1, 1, 1)
        self.ui_label_newInvoiceCandS_clickBelowToSend = QtWidgets.QLabel(self.gridLayoutWidget)
        self.ui_label_newInvoiceCandS_clickBelowToSend.setObjectName("ui_label_newInvoiceCandS_clickBelowToSend")
        self.ui_layout_newInvoiceCandS.addWidget(self.ui_label_newInvoiceCandS_clickBelowToSend, 17, 5, 1, 1)
        self.ui_label_newInvoiceCandS_orderNumber = QtWidgets.QLabel(self.gridLayoutWidget)
        self.ui_label_newInvoiceCandS_orderNumber.setObjectName("ui_label_newInvoiceCandS_orderNumber")
        self.ui_layout_newInvoiceCandS.addWidget(self.ui_label_newInvoiceCandS_orderNumber, 11, 3, 1, 1)
        self.ui_ListView_newInvoiceCandS_orderSearchList = QtWidgets.QListView(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_ListView_newInvoiceCandS_orderSearchList.sizePolicy().hasHeightForWidth())
        self.ui_ListView_newInvoiceCandS_orderSearchList.setSizePolicy(sizePolicy)
        self.ui_ListView_newInvoiceCandS_orderSearchList.setObjectName("ui_ListView_newInvoiceCandS_orderSearchList")
        self.ui_layout_newInvoiceCandS.addWidget(self.ui_ListView_newInvoiceCandS_orderSearchList, 7, 1, 10, 1)
        self.ux_lineEdit_newInvoiceCandS_orderNumber = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.ux_lineEdit_newInvoiceCandS_orderNumber.setObjectName("ux_lineEdit_newInvoiceCandS_orderNumber")
        self.ui_layout_newInvoiceCandS.addWidget(self.ux_lineEdit_newInvoiceCandS_orderNumber, 11, 5, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.ui_layout_newInvoiceCandS.addItem(spacerItem6, 20, 1, 1, 1)
        self.ux_pButton_newInvoiceCandS_createAndSendInvoice = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_pButton_newInvoiceCandS_createAndSendInvoice.sizePolicy().hasHeightForWidth())
        self.ux_pButton_newInvoiceCandS_createAndSendInvoice.setSizePolicy(sizePolicy)
        self.ux_pButton_newInvoiceCandS_createAndSendInvoice.setObjectName("ux_pButton_newInvoiceCandS_createAndSendInvoice")
        self.ui_layout_newInvoiceCandS.addWidget(self.ux_pButton_newInvoiceCandS_createAndSendInvoice, 18, 5, 2, 1)


        self.retranslateUi(MainWindow_mainView)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_mainView)

    def retranslateUi(self, MainWindow_mainView):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_mainView.setWindowTitle(_translate("MainWindow_mainView", "MainWindow"))
        self.ui_label_newInvoiceCandS_orderSubTotal.setText(_translate("MainWindow_mainView", "Order SubTotal:"))
        self.ui_label_newInvoiceCandS_addressLine1.setText(_translate("MainWindow_mainView", "Client Address Line 1:"))
        self.ui_label_newInvoiceCandS_clientEmail.setText(_translate("MainWindow_mainView", "Client Email:"))
        self.ui_label_newInvoiceCandS_addressLine2.setText(_translate("MainWindow_mainView", "Client Address Line 2:"))
        self.ui_label_newInvoiceCandS_header.setText(_translate("MainWindow_mainView", "Create and Send New Invoice"))
        self.ux_pButton_newInvoiceCandS_showAllOrders.setText(_translate("MainWindow_mainView", "Show All Orders"))
        self.ui_label_newInvoiceCandS_clientPhone.setText(_translate("MainWindow_mainView", "Client Phone:"))
        self.ui_label_newInvoiceCandS_orderTotal.setText(_translate("MainWindow_mainView", "Order Total:"))
        self.ui_label_newInvoiceCandS_taxApplied.setText(_translate("MainWindow_mainView", "Tax Applied (in %):"))
        self.ui_label_newInvoiceCandS_clientName.setText(_translate("MainWindow_mainView", "Client Name:"))
        self.ui_label_newInvoiceCandS_orderItems.setText(_translate("MainWindow_mainView", "Order Items:"))
        self.ux_pButton_newInvoiceCandS_ShowUnsentOrders.setText(_translate("MainWindow_mainView", "Show Orders without Invoices Sent"))
        self.ui_label_newInvoiceCandS_doubleClickTo.setText(_translate("MainWindow_mainView", "Double-Click on an Order Number to Show Orders Details:"))
        self.ui_label_newInvoiceCandS_clickBelowToSend.setText(_translate("MainWindow_mainView", "Click Below to Bring-Up your Default Email Client with"))
        self.ui_label_newInvoiceCandS_orderNumber.setText(_translate("MainWindow_mainView", "Order Number:"))
        self.ux_pButton_newInvoiceCandS_createAndSendInvoice.setText(_translate("MainWindow_mainView", "Create And Send Invoice"))
