# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_v5_newProduct.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_mainView(object):
    def setupUi(self, MainWindow_mainView):
        MainWindow_mainView.setObjectName("MainWindow_mainView")
        MainWindow_mainView.resize(1196, 711)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow_mainView.sizePolicy().hasHeightForWidth())
        MainWindow_mainView.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow_mainView)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(310, 20, 871, 681))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.ui_layout_dynamicMainView = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.ui_layout_dynamicMainView.setContentsMargins(0, 0, 0, 0)
        self.ui_layout_dynamicMainView.setObjectName("ui_layout_dynamicMainView")
        self.ui_layout_newProduct = QtWidgets.QGridLayout()
        self.ui_layout_newProduct.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.ui_layout_newProduct.setSpacing(6)
        self.ui_layout_newProduct.setObjectName("ui_layout_newProduct")
        self.ux_lineEdit_newProduct_name = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_lineEdit_newProduct_name.sizePolicy().hasHeightForWidth())
        self.ux_lineEdit_newProduct_name.setSizePolicy(sizePolicy)
        self.ux_lineEdit_newProduct_name.setMinimumSize(QtCore.QSize(200, 0))
        self.ux_lineEdit_newProduct_name.setObjectName("ux_lineEdit_newProduct_name")
        self.ui_layout_newProduct.addWidget(self.ux_lineEdit_newProduct_name, 2, 1, 1, 2)
        self.ux_label_newProduct_price = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_label_newProduct_price.sizePolicy().hasHeightForWidth())
        self.ux_label_newProduct_price.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ux_label_newProduct_price.setFont(font)
        self.ux_label_newProduct_price.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ux_label_newProduct_price.setObjectName("ux_label_newProduct_price")
        self.ui_layout_newProduct.addWidget(self.ux_label_newProduct_price, 6, 0, 1, 1)
        self.ux_lineEdit_newProduct_price = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_lineEdit_newProduct_price.sizePolicy().hasHeightForWidth())
        self.ux_lineEdit_newProduct_price.setSizePolicy(sizePolicy)
        self.ux_lineEdit_newProduct_price.setMinimumSize(QtCore.QSize(200, 0))
        self.ux_lineEdit_newProduct_price.setObjectName("ux_lineEdit_newProduct_price")
        self.ui_layout_newProduct.addWidget(self.ux_lineEdit_newProduct_price, 6, 1, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.ui_layout_newProduct.addItem(spacerItem, 1, 1, 1, 2)
        self.ux_label_newProduct_name = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_label_newProduct_name.sizePolicy().hasHeightForWidth())
        self.ux_label_newProduct_name.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ux_label_newProduct_name.setFont(font)
        self.ux_label_newProduct_name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ux_label_newProduct_name.setObjectName("ux_label_newProduct_name")
        self.ui_layout_newProduct.addWidget(self.ux_label_newProduct_name, 2, 0, 1, 1)
        self.ux_label_newProduct_description = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_label_newProduct_description.sizePolicy().hasHeightForWidth())
        self.ux_label_newProduct_description.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ux_label_newProduct_description.setFont(font)
        self.ux_label_newProduct_description.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ux_label_newProduct_description.setObjectName("ux_label_newProduct_description")
        self.ui_layout_newProduct.addWidget(self.ux_label_newProduct_description, 5, 0, 1, 1)
        self.ux_pButton_newProduct_addProd = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ux_pButton_newProduct_addProd.setMinimumSize(QtCore.QSize(0, 50))
        self.ux_pButton_newProduct_addProd.setObjectName("ux_pButton_newProduct_addProd")
        self.ui_layout_newProduct.addWidget(self.ux_pButton_newProduct_addProd, 11, 3, 1, 1)
        self.ui_label_newProduct_header = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_label_newProduct_header.sizePolicy().hasHeightForWidth())
        self.ui_label_newProduct_header.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.ui_label_newProduct_header.setFont(font)
        self.ui_label_newProduct_header.setAlignment(QtCore.Qt.AlignCenter)
        self.ui_label_newProduct_header.setObjectName("ui_label_newProduct_header")
        self.ui_layout_newProduct.addWidget(self.ui_label_newProduct_header, 0, 0, 1, 4)
        self.ux_textEdit_newProduct_description = QtWidgets.QTextEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_textEdit_newProduct_description.sizePolicy().hasHeightForWidth())
        self.ux_textEdit_newProduct_description.setSizePolicy(sizePolicy)
        self.ux_textEdit_newProduct_description.setObjectName("ux_textEdit_newProduct_description")
        self.ui_layout_newProduct.addWidget(self.ux_textEdit_newProduct_description, 5, 1, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ui_layout_newProduct.addItem(spacerItem1, 10, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.ui_layout_newProduct.addItem(spacerItem2, 11, 2, 1, 1)
        self.ui_layout_dynamicMainView.addLayout(self.ui_layout_newProduct, 0, 0, 1, 1)
        MainWindow_mainView.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow_mainView)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_mainView)

    def retranslateUi(self, MainWindow_mainView):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_mainView.setWindowTitle(_translate("MainWindow_mainView", "MainWindow"))
        self.ux_label_newProduct_price.setText(_translate("MainWindow_mainView", "Product Price-Per-Unit:"))
        self.ux_label_newProduct_name.setText(_translate("MainWindow_mainView", "Product Name:"))
        self.ux_label_newProduct_description.setText(_translate("MainWindow_mainView", "Product Description:"))
        self.ux_pButton_newProduct_addProd.setText(_translate("MainWindow_mainView", "Add New Product To Database"))
        self.ui_label_newProduct_header.setText(_translate("MainWindow_mainView", "Add New Products"))
