# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_main_ui_v4_searchEditClient.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_mainView(object):
    def setupUi(self, MainWindow_mainView):
        MainWindow_mainView.setObjectName("MainWindow_mainView")
        MainWindow_mainView.resize(1196, 711)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow_mainView.sizePolicy().hasHeightForWidth())
        MainWindow_mainView.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow_mainView)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, 0, 131, 721))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.ui_vLayout_viewMain = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.ui_vLayout_viewMain.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.ui_vLayout_viewMain.setContentsMargins(0, 0, 0, 0)
        self.ui_vLayout_viewMain.setSpacing(0)
        self.ui_vLayout_viewMain.setObjectName("ui_vLayout_viewMain")
        self.ux_pButton_orders = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_pButton_orders.sizePolicy().hasHeightForWidth())
        self.ux_pButton_orders.setSizePolicy(sizePolicy)
        self.ux_pButton_orders.setBaseSize(QtCore.QSize(0, 0))
        self.ux_pButton_orders.setObjectName("ux_pButton_orders")
        self.ui_vLayout_viewMain.addWidget(self.ux_pButton_orders)
        self.ux_pButton_clients = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_pButton_clients.sizePolicy().hasHeightForWidth())
        self.ux_pButton_clients.setSizePolicy(sizePolicy)
        self.ux_pButton_clients.setObjectName("ux_pButton_clients")
        self.ui_vLayout_viewMain.addWidget(self.ux_pButton_clients)
        self.ux_pButton_products = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_pButton_products.sizePolicy().hasHeightForWidth())
        self.ux_pButton_products.setSizePolicy(sizePolicy)
        self.ux_pButton_products.setObjectName("ux_pButton_products")
        self.ui_vLayout_viewMain.addWidget(self.ux_pButton_products)
        self.ux_pButton_invoicing = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_pButton_invoicing.sizePolicy().hasHeightForWidth())
        self.ux_pButton_invoicing.setSizePolicy(sizePolicy)
        self.ux_pButton_invoicing.setObjectName("ux_pButton_invoicing")
        self.ui_vLayout_viewMain.addWidget(self.ux_pButton_invoicing)
        self.ux_pButton_statistics = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_pButton_statistics.sizePolicy().hasHeightForWidth())
        self.ux_pButton_statistics.setSizePolicy(sizePolicy)
        self.ux_pButton_statistics.setObjectName("ux_pButton_statistics")
        self.ui_vLayout_viewMain.addWidget(self.ux_pButton_statistics)
        self.ux_pButton_settings = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_pButton_settings.sizePolicy().hasHeightForWidth())
        self.ux_pButton_settings.setSizePolicy(sizePolicy)
        self.ux_pButton_settings.setObjectName("ux_pButton_settings")
        self.ui_vLayout_viewMain.addWidget(self.ux_pButton_settings)
        self.ux_pButton_searchEditOrders = QtWidgets.QPushButton(self.centralwidget)
        self.ux_pButton_searchEditOrders.setGeometry(QtCore.QRect(130, 60, 161, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_pButton_searchEditOrders.sizePolicy().hasHeightForWidth())
        self.ux_pButton_searchEditOrders.setSizePolicy(sizePolicy)
        self.ux_pButton_searchEditOrders.setObjectName("ux_pButton_searchEditOrders")
        self.ux_pButton_newOrder = QtWidgets.QPushButton(self.centralwidget)
        self.ux_pButton_newOrder.setGeometry(QtCore.QRect(130, 0, 161, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_pButton_newOrder.sizePolicy().hasHeightForWidth())
        self.ux_pButton_newOrder.setSizePolicy(sizePolicy)
        self.ux_pButton_newOrder.setObjectName("ux_pButton_newOrder")





        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(310, 20, 871, 681))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.ui_layout_dynamicMainView = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.ui_layout_dynamicMainView.setContentsMargins(0, 0, 0, 0)
        self.ui_layout_dynamicMainView.setObjectName("ui_layout_dynamicMainView")
        self.ui_layout_searchEditClients = QtWidgets.QGridLayout()
        self.ui_layout_searchEditClients.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.ui_layout_searchEditClients.setSpacing(6)
        self.ui_layout_searchEditClients.setObjectName("ui_layout_searchEditClients")
        self.ui_ListView_searchEditClients_nameSearchList = QtWidgets.QListView(self.gridLayoutWidget)
        self.ui_ListView_searchEditClients_nameSearchList.setObjectName("ui_ListView_searchEditClients_nameSearchList")
        self.ui_layout_searchEditClients.addWidget(self.ui_ListView_searchEditClients_nameSearchList, 8, 1, 7, 1)
        self.ui_label_searchEditClients_header = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_label_searchEditClients_header.sizePolicy().hasHeightForWidth())
        self.ui_label_searchEditClients_header.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.ui_label_searchEditClients_header.setFont(font)
        self.ui_label_searchEditClients_header.setAlignment(QtCore.Qt.AlignCenter)
        self.ui_label_searchEditClients_header.setObjectName("ui_label_searchEditClients_header")
        self.ui_layout_searchEditClients.addWidget(self.ui_label_searchEditClients_header, 0, 1, 1, 5)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.ui_layout_searchEditClients.addItem(spacerItem, 13, 5, 1, 1)
        self.ui_label_searchEditClients_typeBelow = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_label_searchEditClients_typeBelow.sizePolicy().hasHeightForWidth())
        self.ui_label_searchEditClients_typeBelow.setSizePolicy(sizePolicy)
        self.ui_label_searchEditClients_typeBelow.setObjectName("ui_label_searchEditClients_typeBelow")
        self.ui_layout_searchEditClients.addWidget(self.ui_label_searchEditClients_typeBelow, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ui_layout_searchEditClients.addItem(spacerItem1, 8, 6, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.ui_layout_searchEditClients.addItem(spacerItem2, 1, 2, 1, 1)
        self.ui_label_searchEditClients_clientEmail = QtWidgets.QLabel(self.gridLayoutWidget)
        self.ui_label_searchEditClients_clientEmail.setObjectName("ui_label_searchEditClients_clientEmail")
        self.ui_layout_searchEditClients.addWidget(self.ui_label_searchEditClients_clientEmail, 12, 3, 1, 1)
        self.ui_label_searchEditClients_doubleClickTo = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_label_searchEditClients_doubleClickTo.sizePolicy().hasHeightForWidth())
        self.ui_label_searchEditClients_doubleClickTo.setSizePolicy(sizePolicy)
        self.ui_label_searchEditClients_doubleClickTo.setObjectName("ui_label_searchEditClients_doubleClickTo")
        self.ui_layout_searchEditClients.addWidget(self.ui_label_searchEditClients_doubleClickTo, 5, 1, 1, 1)
        self.ux_lineEdit_searchEditClients_clientNameSearch = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.ux_lineEdit_searchEditClients_clientNameSearch.setObjectName("ux_lineEdit_searchEditClients_clientNameSearch")
        self.ui_layout_searchEditClients.addWidget(self.ux_lineEdit_searchEditClients_clientNameSearch, 3, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ui_layout_searchEditClients.addItem(spacerItem3, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.ui_layout_searchEditClients.addItem(spacerItem4, 15, 1, 2, 1)
        self.ui_label_searchEditClients_clientName = QtWidgets.QLabel(self.gridLayoutWidget)
        self.ui_label_searchEditClients_clientName.setObjectName("ui_label_searchEditClients_clientName")
        self.ui_layout_searchEditClients.addWidget(self.ui_label_searchEditClients_clientName, 8, 3, 1, 1)
        self.ui_label_searchEditClients_addressLine2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.ui_label_searchEditClients_addressLine2.setObjectName("ui_label_searchEditClients_addressLine2")
        self.ui_layout_searchEditClients.addWidget(self.ui_label_searchEditClients_addressLine2, 10, 3, 1, 1)
        self.ui_label_searchEditClients_addressLine1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.ui_label_searchEditClients_addressLine1.setObjectName("ui_label_searchEditClients_addressLine1")
        self.ui_layout_searchEditClients.addWidget(self.ui_label_searchEditClients_addressLine1, 9, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ui_layout_searchEditClients.addItem(spacerItem5, 3, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ui_layout_searchEditClients.addItem(spacerItem6, 8, 4, 1, 1)
        self.ui_label_searchEditClients_clientPhone = QtWidgets.QLabel(self.gridLayoutWidget)
        self.ui_label_searchEditClients_clientPhone.setObjectName("ui_label_searchEditClients_clientPhone")
        self.ui_layout_searchEditClients.addWidget(self.ui_label_searchEditClients_clientPhone, 11, 3, 1, 1)
        self.ux_pButton_searchEditClients_editClientInfo = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ux_pButton_searchEditClients_editClientInfo.setObjectName("ux_pButton_searchEditClients_editClientInfo")
        self.ui_layout_searchEditClients.addWidget(self.ux_pButton_searchEditClients_editClientInfo, 14, 3, 1, 1)
        self.ux_lineEdit_searchEditClients_cNameOut = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.ux_lineEdit_searchEditClients_cNameOut.setObjectName("ux_lineEdit_searchEditClients_cNameOut")
        self.ui_layout_searchEditClients.addWidget(self.ux_lineEdit_searchEditClients_cNameOut, 8, 5, 1, 1)
        self.ux_lineEdit_searchEditClients_address1Out = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.ux_lineEdit_searchEditClients_address1Out.setObjectName("ux_lineEdit_searchEditClients_address1Out")
        self.ui_layout_searchEditClients.addWidget(self.ux_lineEdit_searchEditClients_address1Out, 9, 5, 1, 1)
        self.ux_lineEdit_searchEditClients_address2Out = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.ux_lineEdit_searchEditClients_address2Out.setObjectName("ux_lineEdit_searchEditClients_address2Out")
        self.ui_layout_searchEditClients.addWidget(self.ux_lineEdit_searchEditClients_address2Out, 10, 5, 1, 1)
        self.ux_lineEdit_searchEditClients_cPhoneOut = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.ux_lineEdit_searchEditClients_cPhoneOut.setObjectName("ux_lineEdit_searchEditClients_cPhoneOut")
        self.ui_layout_searchEditClients.addWidget(self.ux_lineEdit_searchEditClients_cPhoneOut, 11, 5, 1, 1)
        self.ux_lineEdit_searchEditClients_cEmailOut = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.ux_lineEdit_searchEditClients_cEmailOut.setObjectName("ux_lineEdit_searchEditClients_cEmailOut")
        self.ui_layout_searchEditClients.addWidget(self.ux_lineEdit_searchEditClients_cEmailOut, 12, 5, 1, 1)
        self.ux_pButton_searchEditClients_finalizeInfo = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ux_pButton_searchEditClients_finalizeInfo.setObjectName("ux_pButton_searchEditClients_finalizeInfo")
        self.ui_layout_searchEditClients.addWidget(self.ux_pButton_searchEditClients_finalizeInfo, 14, 5, 1, 1)
        self.ui_layout_dynamicMainView.addLayout(self.ui_layout_searchEditClients, 1, 0, 1, 1)
        self.ux_pButton_newClient = QtWidgets.QPushButton(self.centralwidget)
        self.ux_pButton_newClient.setGeometry(QtCore.QRect(130, 120, 161, 61))
        self.ux_pButton_newClient.setObjectName("ux_pButton_newClient")
        self.ux_pButton_editClient = QtWidgets.QPushButton(self.centralwidget)
        self.ux_pButton_editClient.setGeometry(QtCore.QRect(130, 180, 161, 60))
        self.ux_pButton_editClient.setObjectName("ux_pButton_editClient")
        self.ux_pButton_addProduct = QtWidgets.QPushButton(self.centralwidget)
        self.ux_pButton_addProduct.setGeometry(QtCore.QRect(130, 240, 161, 61))
        self.ux_pButton_addProduct.setObjectName("ux_pButton_addProduct")
        self.ux_pButton_editProduct = QtWidgets.QPushButton(self.centralwidget)
        self.ux_pButton_editProduct.setGeometry(QtCore.QRect(130, 300, 161, 61))
        self.ux_pButton_editProduct.setObjectName("ux_pButton_editProduct")
        self.ux_pButton_newInvoice = QtWidgets.QPushButton(self.centralwidget)
        self.ux_pButton_newInvoice.setGeometry(QtCore.QRect(130, 360, 161, 41))
        self.ux_pButton_newInvoice.setObjectName("ux_pButton_newInvoice")
        self.ux_pButton_sendInvoice = QtWidgets.QPushButton(self.centralwidget)
        self.ux_pButton_sendInvoice.setGeometry(QtCore.QRect(130, 400, 161, 41))
        self.ux_pButton_sendInvoice.setObjectName("ux_pButton_sendInvoice")
        self.ux_pButton_searchInvoice = QtWidgets.QPushButton(self.centralwidget)
        self.ux_pButton_searchInvoice.setGeometry(QtCore.QRect(130, 440, 161, 41))
        self.ux_pButton_searchInvoice.setObjectName("ux_pButton_searchInvoice")
        self.ux_pButton_summaryView = QtWidgets.QPushButton(self.centralwidget)
        self.ux_pButton_summaryView.setGeometry(QtCore.QRect(130, 480, 161, 61))
        self.ux_pButton_summaryView.setObjectName("ux_pButton_summaryView")
        self.ux_pButton_searchView = QtWidgets.QPushButton(self.centralwidget)
        self.ux_pButton_searchView.setGeometry(QtCore.QRect(130, 540, 161, 61))
        self.ux_pButton_searchView.setObjectName("ux_pButton_searchView")
        MainWindow_mainView.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow_mainView)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_mainView)

    def retranslateUi(self, MainWindow_mainView):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_mainView.setWindowTitle(_translate("main_view", "MainWindow"))
        self.ux_pButton_orders.setText(_translate("main_view", "Orders"))
        self.ux_pButton_clients.setText(_translate("main_view", "Clients"))
        self.ux_pButton_products.setText(_translate("MainWindow_mainView", "Products"))
        self.ux_pButton_invoicing.setText(_translate("MainWindow_mainView", "Invoicing"))
        self.ux_pButton_statistics.setText(_translate("MainWindow_mainView", "Statistics"))
        self.ux_pButton_settings.setText(_translate("MainWindow_mainView", "Settings"))
        self.ux_pButton_searchEditOrders.setText(_translate("MainWindow_mainView", "Search/Edit Orders"))
        self.ux_pButton_newOrder.setText(_translate("MainWindow_mainView", "New Order"))
        self.ui_label_searchEditClients_header.setText(_translate("MainWindow_mainView", "Search/Edit Client Information"))
        self.ui_label_searchEditClients_typeBelow.setText(_translate("MainWindow_mainView", "Type a Clent Name Below to Search:"))
        self.ui_label_searchEditClients_clientEmail.setText(_translate("MainWindow_mainView", "Client Email:"))
        self.ui_label_searchEditClients_doubleClickTo.setText(_translate("MainWindow_mainView", "Double-Click on Client Name Below to Show Information:"))
        self.ui_label_searchEditClients_clientName.setText(_translate("MainWindow_mainView", "Client Name:"))
        self.ui_label_searchEditClients_addressLine2.setText(_translate("MainWindow_mainView", "Client Address Line 2:"))
        self.ui_label_searchEditClients_addressLine1.setText(_translate("MainWindow_mainView", "Client Address Line 1:"))
        self.ui_label_searchEditClients_clientPhone.setText(_translate("MainWindow_mainView", "Client Phone:"))
        self.ux_pButton_searchEditClients_editClientInfo.setText(_translate("MainWindow_mainView", "Edit Client Information"))
        self.ux_pButton_searchEditClients_finalizeInfo.setText(_translate("MainWindow_mainView", "Finalize Information Edit"))
        self.ux_pButton_newClient.setText(_translate("MainWindow_mainView", "Add New Client"))
        self.ux_pButton_editClient.setText(_translate("MainWindow_mainView", "Search/Edit Client Info."))
        self.ux_pButton_addProduct.setText(_translate("MainWindow_mainView", "Add New Product"))
        self.ux_pButton_editProduct.setText(_translate("MainWindow_mainView", "Search/Edit Product Info."))
        self.ux_pButton_newInvoice.setText(_translate("MainWindow_mainView", "Create New Invoice"))
        self.ux_pButton_sendInvoice.setText(_translate("MainWindow_mainView", "Send Invoice(s)"))
        self.ux_pButton_searchInvoice.setText(_translate("MainWindow_mainView", "Search Invoices"))
        self.ux_pButton_summaryView.setText(_translate("MainWindow_mainView", "Summary View"))
        self.ux_pButton_searchView.setText(_translate("MainWindow_mainView", "Search and View"))
