# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newMenuButtons.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(467, 795)
        self.ui_widget_menuButtons = QtWidgets.QWidget(Form)
        self.ui_widget_menuButtons.setGeometry(QtCore.QRect(170, 60, 181, 621))
        self.ui_widget_menuButtons.setObjectName("ui_widget_menuButtons")
        self.ui_gridLayout_menuButtons = QtWidgets.QGridLayout(self.ui_widget_menuButtons)
        self.ui_gridLayout_menuButtons.setContentsMargins(0, 0, 0, 0)
        self.ui_gridLayout_menuButtons.setSpacing(0)
        self.ui_gridLayout_menuButtons.setObjectName("ui_gridLayout_menuButtons")
        self.ux_pButton_sendMultInvoices = QtWidgets.QPushButton(self.ui_widget_menuButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_pButton_sendMultInvoices.sizePolicy().hasHeightForWidth())
        self.ux_pButton_sendMultInvoices.setSizePolicy(sizePolicy)
        self.ux_pButton_sendMultInvoices.setObjectName("ux_pButton_sendMultInvoices")
        self.ui_gridLayout_menuButtons.addWidget(self.ux_pButton_sendMultInvoices, 14, 1, 1, 1)
        self.ux_pButton_Settings = QtWidgets.QPushButton(self.ui_widget_menuButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_pButton_Settings.sizePolicy().hasHeightForWidth())
        self.ux_pButton_Settings.setSizePolicy(sizePolicy)
        self.ux_pButton_Settings.setObjectName("ux_pButton_Settings")
        self.ui_gridLayout_menuButtons.addWidget(self.ux_pButton_Settings, 18, 0, 1, 3)
        self.ux_pButton_Products = QtWidgets.QPushButton(self.ui_widget_menuButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_pButton_Products.sizePolicy().hasHeightForWidth())
        self.ux_pButton_Products.setSizePolicy(sizePolicy)
        self.ux_pButton_Products.setObjectName("ux_pButton_Products")
        self.ui_gridLayout_menuButtons.addWidget(self.ux_pButton_Products, 7, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ui_gridLayout_menuButtons.addItem(spacerItem, 1, 0, 3, 1)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ui_gridLayout_menuButtons.addItem(spacerItem1, 1, 2, 2, 1)
        self.ux_pButton_sendInvoice = QtWidgets.QPushButton(self.ui_widget_menuButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_pButton_sendInvoice.sizePolicy().hasHeightForWidth())
        self.ux_pButton_sendInvoice.setSizePolicy(sizePolicy)
        self.ux_pButton_sendInvoice.setObjectName("ux_pButton_sendInvoice")
        self.ui_gridLayout_menuButtons.addWidget(self.ux_pButton_sendInvoice, 13, 1, 1, 1)
        self.ux_pButton_newOrder = QtWidgets.QPushButton(self.ui_widget_menuButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_pButton_newOrder.sizePolicy().hasHeightForWidth())
        self.ux_pButton_newOrder.setSizePolicy(sizePolicy)
        self.ux_pButton_newOrder.setObjectName("ux_pButton_newOrder")
        self.ui_gridLayout_menuButtons.addWidget(self.ux_pButton_newOrder, 1, 1, 1, 1)
        self.ux_pButton_searchEditClients = QtWidgets.QPushButton(self.ui_widget_menuButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_pButton_searchEditClients.sizePolicy().hasHeightForWidth())
        self.ux_pButton_searchEditClients.setSizePolicy(sizePolicy)
        self.ux_pButton_searchEditClients.setObjectName("ux_pButton_searchEditClients")
        self.ui_gridLayout_menuButtons.addWidget(self.ux_pButton_searchEditClients, 6, 1, 1, 1)
        self.ux_pButton_searchEditOrders = QtWidgets.QPushButton(self.ui_widget_menuButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_pButton_searchEditOrders.sizePolicy().hasHeightForWidth())
        self.ux_pButton_searchEditOrders.setSizePolicy(sizePolicy)
        self.ux_pButton_searchEditOrders.setObjectName("ux_pButton_searchEditOrders")
        self.ui_gridLayout_menuButtons.addWidget(self.ux_pButton_searchEditOrders, 2, 1, 1, 1)
        self.ux_pButton_Orders = QtWidgets.QPushButton(self.ui_widget_menuButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_pButton_Orders.sizePolicy().hasHeightForWidth())
        self.ux_pButton_Orders.setSizePolicy(sizePolicy)
        self.ux_pButton_Orders.setObjectName("ux_pButton_Orders")
        self.ui_gridLayout_menuButtons.addWidget(self.ux_pButton_Orders, 0, 0, 1, 3)
        self.ux_pButton_searchEditInvoices = QtWidgets.QPushButton(self.ui_widget_menuButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_pButton_searchEditInvoices.sizePolicy().hasHeightForWidth())
        self.ux_pButton_searchEditInvoices.setSizePolicy(sizePolicy)
        self.ux_pButton_searchEditInvoices.setObjectName("ux_pButton_searchEditInvoices")
        self.ui_gridLayout_menuButtons.addWidget(self.ux_pButton_searchEditInvoices, 12, 1, 1, 1)
        self.ux_pButton_searchEditProducts = QtWidgets.QPushButton(self.ui_widget_menuButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_pButton_searchEditProducts.sizePolicy().hasHeightForWidth())
        self.ux_pButton_searchEditProducts.setSizePolicy(sizePolicy)
        self.ux_pButton_searchEditProducts.setObjectName("ux_pButton_searchEditProducts")
        self.ui_gridLayout_menuButtons.addWidget(self.ux_pButton_searchEditProducts, 9, 1, 1, 1)
        self.ux_pButton_Statistics = QtWidgets.QPushButton(self.ui_widget_menuButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_pButton_Statistics.sizePolicy().hasHeightForWidth())
        self.ux_pButton_Statistics.setSizePolicy(sizePolicy)
        self.ux_pButton_Statistics.setObjectName("ux_pButton_Statistics")
        self.ui_gridLayout_menuButtons.addWidget(self.ux_pButton_Statistics, 15, 0, 1, 3)
        self.ux_pButton_Invoicing = QtWidgets.QPushButton(self.ui_widget_menuButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_pButton_Invoicing.sizePolicy().hasHeightForWidth())
        self.ux_pButton_Invoicing.setSizePolicy(sizePolicy)
        self.ux_pButton_Invoicing.setObjectName("ux_pButton_Invoicing")
        self.ui_gridLayout_menuButtons.addWidget(self.ux_pButton_Invoicing, 10, 0, 1, 3)
        self.ux_pButton_Clients = QtWidgets.QPushButton(self.ui_widget_menuButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_pButton_Clients.sizePolicy().hasHeightForWidth())
        self.ux_pButton_Clients.setSizePolicy(sizePolicy)
        self.ux_pButton_Clients.setObjectName("ux_pButton_Clients")
        self.ui_gridLayout_menuButtons.addWidget(self.ux_pButton_Clients, 4, 0, 1, 3)
        self.ux_pButton_addClient = QtWidgets.QPushButton(self.ui_widget_menuButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_pButton_addClient.sizePolicy().hasHeightForWidth())
        self.ux_pButton_addClient.setSizePolicy(sizePolicy)
        self.ux_pButton_addClient.setObjectName("ux_pButton_addClient")
        self.ui_gridLayout_menuButtons.addWidget(self.ux_pButton_addClient, 5, 1, 1, 1)
        self.ux_pButton_newInvoice = QtWidgets.QPushButton(self.ui_widget_menuButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_pButton_newInvoice.sizePolicy().hasHeightForWidth())
        self.ux_pButton_newInvoice.setSizePolicy(sizePolicy)
        self.ux_pButton_newInvoice.setObjectName("ux_pButton_newInvoice")
        self.ui_gridLayout_menuButtons.addWidget(self.ux_pButton_newInvoice, 11, 1, 1, 1)
        self.ux_pButton_addProduct = QtWidgets.QPushButton(self.ui_widget_menuButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_pButton_addProduct.sizePolicy().hasHeightForWidth())
        self.ux_pButton_addProduct.setSizePolicy(sizePolicy)
        self.ux_pButton_addProduct.setObjectName("ux_pButton_addProduct")
        self.ui_gridLayout_menuButtons.addWidget(self.ux_pButton_addProduct, 8, 1, 1, 1)
        self.ux_pButton_summaryView = QtWidgets.QPushButton(self.ui_widget_menuButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_pButton_summaryView.sizePolicy().hasHeightForWidth())
        self.ux_pButton_summaryView.setSizePolicy(sizePolicy)
        self.ux_pButton_summaryView.setObjectName("ux_pButton_summaryView")
        self.ui_gridLayout_menuButtons.addWidget(self.ux_pButton_summaryView, 16, 1, 1, 1)
        self.ux_pButton_searchAndView = QtWidgets.QPushButton(self.ui_widget_menuButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ux_pButton_searchAndView.sizePolicy().hasHeightForWidth())
        self.ux_pButton_searchAndView.setSizePolicy(sizePolicy)
        self.ux_pButton_searchAndView.setObjectName("ux_pButton_searchAndView")
        self.ui_gridLayout_menuButtons.addWidget(self.ux_pButton_searchAndView, 17, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ui_gridLayout_menuButtons.addItem(spacerItem2, 5, 2, 2, 1)
        spacerItem3 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ui_gridLayout_menuButtons.addItem(spacerItem3, 5, 0, 2, 1)
        spacerItem4 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ui_gridLayout_menuButtons.addItem(spacerItem4, 8, 2, 2, 1)
        spacerItem5 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ui_gridLayout_menuButtons.addItem(spacerItem5, 8, 0, 2, 1)
        spacerItem6 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ui_gridLayout_menuButtons.addItem(spacerItem6, 11, 0, 4, 1)
        spacerItem7 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ui_gridLayout_menuButtons.addItem(spacerItem7, 11, 2, 4, 1)
        spacerItem8 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ui_gridLayout_menuButtons.addItem(spacerItem8, 16, 2, 2, 1)
        spacerItem9 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ui_gridLayout_menuButtons.addItem(spacerItem9, 16, 0, 2, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.ux_pButton_sendMultInvoices.setText(_translate("Form", "Send Multiple Invoices"))
        self.ux_pButton_Settings.setText(_translate("Form", "Settings"))
        self.ux_pButton_Products.setText(_translate("Form", "Products"))
        self.ux_pButton_sendInvoice.setText(_translate("Form", "Send An Invoice"))
        self.ux_pButton_newOrder.setText(_translate("Form", "Create A New Order"))
        self.ux_pButton_searchEditClients.setText(_translate("Form", "Search/Edit Clients"))
        self.ux_pButton_searchEditOrders.setText(_translate("Form", "Search/Edit Orders"))
        self.ux_pButton_Orders.setText(_translate("Form", "Orders"))
        self.ux_pButton_searchEditInvoices.setText(_translate("Form", "Search/Edit Invoices"))
        self.ux_pButton_searchEditProducts.setText(_translate("Form", "Search/Edit Products"))
        self.ux_pButton_Statistics.setText(_translate("Form", "Statistics"))
        self.ux_pButton_Invoicing.setText(_translate("Form", "Invoicing"))
        self.ux_pButton_Clients.setText(_translate("Form", "Clients"))
        self.ux_pButton_addClient.setText(_translate("Form", "Add A New Client"))
        self.ux_pButton_newInvoice.setText(_translate("Form", "Create A New Invoice"))
        self.ux_pButton_addProduct.setText(_translate("Form", "Add A New Product"))
        self.ux_pButton_summaryView.setText(_translate("Form", "Summary View"))
        self.ux_pButton_searchAndView.setText(_translate("Form", "Search and View"))
